# -*- coding: utf-8 -*-
"""KD_Datathon_24hrs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15G4satmV3lXLom5HU2r9q8rsE2Vz_7mu
"""

print("hello")

!pip -q install -U google-cloud-bigquery pandas-gbq google-cloud-bigquery-storage



"""Once you've identified a dataset, you can then list the tables within it to pinpoint the exact data you want to load.

# Task
Set up and authenticate Google BigQuery client.

## Import BigQuery Libraries

### Subtask:
Import the necessary Python libraries for interacting with Google BigQuery, such as `google.cloud.bigquery` and `pandas_gbq`.

**Reasoning**:
Import the necessary Python libraries for BigQuery interaction as requested in the subtask.
"""

import pandas_gbq
from google.cloud import bigquery
print("BigQuery libraries imported successfully.")

"""## Authenticate to Google Cloud

### Subtask:
Ensure authentication to Google Cloud is properly set up, typically by using `google.colab.auth.authenticate_user()`.

**Reasoning**:
To authenticate to Google Cloud, I need to import the `authenticate_user` function and then call it to initiate the authentication flow.
"""

from google.colab import auth
auth.authenticate_user()
print("User authenticated to Google Cloud.")

"""## Initialize BigQuery Client

### Subtask:
Initialize the BigQuery client to enable interactions with BigQuery datasets and tables.

**Reasoning**:
To initialize the BigQuery client, I will create an instance of `bigquery.Client()` and print a confirmation message as instructed.
"""

client = bigquery.Client()
print("BigQuery client initialized successfully.")

"""## Final Task

### Subtask:
Confirm that BigQuery is successfully set up and ready for use.

## Summary:

### Q&A
Yes, BigQuery is successfully set up and ready for use.

### Data Analysis Key Findings
*   The necessary BigQuery libraries, `pandas_gbq` and `google.cloud.bigquery`, were successfully imported.
*   User authentication to Google Cloud was successfully completed using `google.colab.auth.authenticate_user()`.
*   The BigQuery client was successfully initialized.

### Insights or Next Steps
*   The environment is now prepared for performing data queries and operations using Google BigQuery.

# Task
Explore all tables within the `eicu_crd`, `mimiciv_3_1_hosp`, and `mimiciv_3_1_icu` datasets in the `physionet-data` BigQuery project.

## Explore Tables in Each Dataset

### Subtask:
Iterate through the `eicu_crd`, `mimiciv_3_1_hosp`, and `mimiciv_3_1_icu` datasets and list all the tables available in each. This will provide an overview of the data structures in each dataset.

**Reasoning**:
To achieve the subtask, I will first define the list of dataset IDs. Then, I will iterate through each dataset, use the BigQuery client to list its tables, and print them to the console.
"""

dataset_ids = ["eicu_crd", "mimiciv_3_1_hosp", "mimiciv_3_1_icu"]
project_to_explore = "physionet-data"

for dataset_id in dataset_ids:
    print(f"\nTables in dataset '{dataset_id}':")
    try:
        tables = list(client.list_tables(f"{project_to_explore}.{dataset_id}"))
        if tables:
            for table in tables:
                print(f"- {table.table_id}")
        else:
            print(f"  No tables found in '{dataset_id}'.")
    except Exception as e:
        print(f"  Error listing tables for '{dataset_id}': {e}")

# Replace 'YOUR_BILLING_PROJECT_ID' with your actual Google Cloud Project ID.
# This project will be used for billing when querying public datasets.
BILLING_PROJECT_ID = "local-store-313510" # e.g., "my-gcp-project-12345"

# Only proceed if a billing project ID is provided.
if BILLING_PROJECT_ID == "YOUR_GCP_PROJECT_ID":
    print("Please update 'BILLING_PROJECT_ID' with your Google Cloud Project ID to query the public dataset.")
else:
    sql_allergy = """
    SELECT *
    FROM `physionet-data.eicu_crd.allergy`
    LIMIT 5
    """
    try:
        # Use pandas_gbq.read_gbq to explicitly disable the BigQuery Storage API,
        # which was causing 'bigquery.readsessions.create' permission errors.
        allergy_df = pandas_gbq.read_gbq(sql_allergy, project_id=BILLING_PROJECT_ID, use_bqstorage_api=False)
        display(allergy_df)
    except Exception as e:
        print(f"Error querying data: {e}")
        print("Please ensure your BILLING_PROJECT_ID is correct and has billing enabled, and that you have permission to query BigQuery.")

# @title 🧮 Build cohort + features (ICU→floor, pressor in last 6h, vitals incl. SBP, demographics, comorbidities, discharge timing)
sql = r"""
-- MIMIC-IV v3.1 (BigQuery) — ICU→floor cohort w/ features for logistic regression

-- 0) Base ICU stays
WITH icu_stays AS (
  SELECT subject_id, hadm_id, stay_id, intime, outtime,
         TIMESTAMP_DIFF(outtime, intime, HOUR) AS icu_los_hours,
         first_careunit, last_careunit
  FROM `physionet-data.mimiciv_3_1_icu.icustays`
  WHERE outtime IS NOT NULL
),

-- 1) Determine ICU careunits (any unit appearing in icustays)
icu_units AS (
  SELECT DISTINCT first_careunit AS icu_unit FROM icu_stays WHERE first_careunit IS NOT NULL
  UNION DISTINCT
  SELECT DISTINCT last_careunit  AS icu_unit FROM icu_stays  WHERE last_careunit  IS NOT NULL
),

-- 2) First destination *after* ICU outtime (within same hadm)
post_icu_segments AS (
  SELECT s.subject_id, s.hadm_id, s.stay_id,
         s.outtime AS t0_transfer,
         t.careunit, t.intime AS seg_start, t.outtime AS seg_end
  FROM icu_stays s
  JOIN `physionet-data.mimiciv_3_1_hosp.transfers` t
    ON t.subject_id = s.subject_id
   AND t.hadm_id    = s.hadm_id
   AND t.intime    >= s.outtime
),
first_after_icu AS (
  SELECT subject_id, hadm_id, stay_id, t0_transfer,
         ARRAY_AGG(STRUCT(careunit, seg_start, seg_end) ORDER BY seg_start)[SAFE_OFFSET(0)] AS first_seg
  FROM post_icu_segments
  GROUP BY subject_id, hadm_id, stay_id, t0_transfer
),

-- 3) Keep ICU→FLOOR (first dest NOT ICU)
icu_to_floor AS (
  SELECT f.subject_id, f.hadm_id, f.stay_id, f.t0_transfer,
         f.first_seg.careunit  AS first_careunit_after_icu
  FROM first_after_icu f
  LEFT JOIN icu_units u ON f.first_seg.careunit = u.icu_unit
  WHERE u.icu_unit IS NULL
),

-- 4) Sequence of ICU stays per HADM to get "prior bounces" and next ICU
icu_seq AS (
  SELECT subject_id, hadm_id, stay_id, intime, outtime,
         ROW_NUMBER() OVER (PARTITION BY subject_id, hadm_id ORDER BY intime) AS icu_seq_num,
         COUNT(*)    OVER (PARTITION BY subject_id, hadm_id)                   AS icu_total_in_hadm,
         LEAD(intime) OVER (PARTITION BY subject_id, hadm_id ORDER BY intime) AS next_icu_in
  FROM `physionet-data.mimiciv_3_1_icu.icustays`
),
link AS (  -- align sequence features to our ICU→floor transfers
  SELECT x.subject_id, x.hadm_id, x.stay_id, x.t0_transfer,
         s.icu_seq_num,
         s.icu_total_in_hadm,
         s.next_icu_in
  FROM icu_to_floor x
  JOIN icu_seq s USING (subject_id, hadm_id, stay_id)
),

-- 5) Rapid ICU readmission labels (same hospitalization)
bounce_labels AS (
  SELECT subject_id, hadm_id, stay_id, t0_transfer,
         next_icu_in,
         TIMESTAMP_DIFF(next_icu_in, t0_transfer, HOUR) AS hours_to_next_icu,
         CASE WHEN next_icu_in IS NOT NULL
                AND TIMESTAMP_DIFF(next_icu_in, t0_transfer, HOUR) BETWEEN 0 AND 24
              THEN 1 ELSE 0 END AS label_readmit_24h,
         CASE WHEN next_icu_in IS NOT NULL
                AND TIMESTAMP_DIFF(next_icu_in, t0_transfer, HOUR) BETWEEN 0 AND 72
              THEN 1 ELSE 0 END AS label_readmit_72h,
         GREATEST(icu_seq_num - 1, 0) AS prior_icu_bounces_in_hadm
  FROM link
),

-- 6) 30-day unplanned readmission (hospital level)
adm AS (
  SELECT subject_id, hadm_id, admittime, dischtime, admission_type,
         language, marital_status, insurance
  FROM `physionet-data.mimiciv_3_1_hosp.admissions`
  WHERE dischtime IS NOT NULL
),
readmit30 AS (
  SELECT subject_id, hadm_id, dischtime,
         LEAD(admittime)      OVER (PARTITION BY subject_id ORDER BY admittime) AS next_admit,
         LEAD(admission_type) OVER (PARTITION BY subject_id ORDER BY admittime) AS next_type
  FROM adm
),
readmit_flags AS (
  SELECT subject_id, hadm_id,
         CASE WHEN next_admit IS NOT NULL
                AND next_admit > dischtime
                AND TIMESTAMP_DIFF(next_admit, dischtime, DAY) <= 30
                AND UPPER(next_type) IN ('EMERGENCY','URGENT')
              THEN 1 ELSE 0 END AS label_readmit30_unplanned
  FROM readmit30
),

-- 7) Patient demo + derived age at transfer
patient_info AS (
  SELECT p.subject_id, p.gender, p.anchor_age, p.anchor_year,
         a.hadm_id, a.language, a.marital_status, a.insurance
  FROM `physionet-data.mimiciv_3_1_hosp.patients` p
  JOIN adm a ON a.subject_id = p.subject_id
),

-- 8) Vasopressors
pressor_items AS (
  SELECT itemid
  FROM `physionet-data.mimiciv_3_1_icu.d_items`
  WHERE LOWER(label) IN ('norepinephrine','epinephrine','phenylephrine','dopamine','vasopressin')
),
pressor_last6h AS (  -- any pressor overlapping (t0-6h, t0)
  SELECT x.subject_id, x.hadm_id, x.stay_id, x.t0_transfer,
         COUNT(*) > 0 AS any_presser_6h
  FROM icu_to_floor x
  JOIN `physionet-data.mimiciv_3_1_icu.inputevents` ie
    ON ie.subject_id = x.subject_id AND ie.hadm_id = x.hadm_id AND ie.stay_id = x.stay_id
  JOIN pressor_items pi ON pi.itemid = ie.itemid
  WHERE COALESCE(ie.endtime, ie.starttime) > TIMESTAMP_SUB(x.t0_transfer, INTERVAL 6 HOUR)
    AND ie.starttime                     < x.t0_transfer
  GROUP BY x.subject_id, x.hadm_id, x.stay_id, x.t0_transfer
),
last_presser_off AS (  -- last endtime before t0
  SELECT x.subject_id, x.hadm_id, x.stay_id, x.t0_transfer,
         MAX(COALESCE(ie.endtime, ie.starttime)) AS last_presser_end
  FROM icu_to_floor x
  JOIN `physionet-data.mimiciv_3_1_icu.inputevents` ie
    ON ie.subject_id = x.subject_id AND ie.hadm_id = x.hadm_id AND ie.stay_id = x.stay_id
  JOIN pressor_items pi ON pi.itemid = ie.itemid
  WHERE COALESCE(ie.endtime, ie.starttime) < x.t0_transfer
  GROUP BY x.subject_id, x.hadm_id, x.stay_id, x.t0_transfer
),

-- 9) Extubation timing (procedureevents itemids like '%extubat%')
extubation_items AS (
  SELECT itemid
  FROM `physionet-data.mimiciv_3_1_icu.d_items`
  WHERE LOWER(label) LIKE '%extubat%'
),
last_extubation AS (
  SELECT x.subject_id, x.hadm_id, x.stay_id, x.t0_transfer,
         MAX(COALESCE(pe.endtime, pe.starttime)) AS last_extubation_time
  FROM icu_to_floor x
  JOIN `physionet-data.mimiciv_3_1_icu.procedureevents` pe
    ON pe.subject_id = x.subject_id AND pe.hadm_id = x.hadm_id AND pe.stay_id = x.stay_id
  JOIN extubation_items ei ON ei.itemid = pe.itemid
  WHERE COALESCE(pe.endtime, pe.starttime) < x.t0_transfer
  GROUP BY x.subject_id, x.hadm_id, x.stay_id, x.t0_transfer
),

-- 10) Vitals in last 6h (HR/RR/MAP/SBP), last value and CV
vital_items AS (
  SELECT itemid, 'HR'  AS var FROM `physionet-data.mimiciv_3_1_icu.d_items` WHERE LOWER(label) = 'heart rate'
  UNION ALL SELECT itemid, 'RR'  FROM `physionet-data.mimiciv_3_1_icu.d_items` WHERE LOWER(label) = 'respiratory rate'
  UNION ALL SELECT itemid, 'MAP' FROM `physionet-data.mimiciv_3_1_icu.d_items`
            WHERE LOWER(label) IN ('non invasive blood pressure mean','mean bp','map (mmhg)')
  UNION ALL SELECT itemid, 'SBP' FROM `physionet-data.mimiciv_3_1_icu.d_items`
            WHERE LOWER(label) IN ('non invasive blood pressure systolic','systolic bp','sbp (mmhg)')
),
vitals_6h AS (
  SELECT c.subject_id, c.hadm_id, c.stay_id,
         v.var, c.charttime, c.valuenum
  FROM `physionet-data.mimiciv_3_1_icu.chartevents` c
  JOIN vital_items v ON v.itemid = c.itemid
  JOIN icu_to_floor x
    ON x.subject_id = c.subject_id AND x.hadm_id = c.hadm_id AND x.stay_id = c.stay_id
  WHERE c.valuenum IS NOT NULL
    AND c.charttime >= TIMESTAMP_SUB(x.t0_transfer, INTERVAL 6 HOUR)
    AND c.charttime <  x.t0_transfer
),
vitals_packed AS (
  SELECT subject_id, hadm_id, stay_id, var,
         ARRAY_AGG(valuenum ORDER BY charttime) AS vals,
         ARRAY_REVERSE(ARRAY_AGG(valuenum ORDER BY charttime))[SAFE_OFFSET(0)] AS last_val
  FROM vitals_6h
  GROUP BY subject_id, hadm_id, stay_id, var
),
vitals_features AS (
  SELECT subject_id, hadm_id, stay_id,
         MAX(IF(var='HR',  last_val, NULL))  AS hr_last,
         MAX(IF(var='RR',  last_val, NULL))  AS rr_last,
         MAX(IF(var='MAP', last_val, NULL))  AS map_last,
         MAX(IF(var='SBP', last_val, NULL))  AS sbp_last,
         MAX(IF(var='HR',  (SELECT SAFE_DIVIDE(STDDEV_SAMP(x), NULLIF(AVG(x),0)) FROM UNNEST(vals) x), NULL))  AS hr_cv6h,
         MAX(IF(var='RR',  (SELECT SAFE_DIVIDE(STDDEV_SAMP(x), NULLIF(AVG(x),0)) FROM UNNEST(vals) x), NULL))  AS rr_cv6h,
         MAX(IF(var='MAP', (SELECT SAFE_DIVIDE(STDDEV_SAMP(x), NULLIF(AVG(x),0)) FROM UNNEST(vals) x), NULL))  AS map_cv6h,
         MAX(IF(var='SBP', (SELECT SAFE_DIVIDE(STDDEV_SAMP(x), NULLIF(AVG(x),0)) FROM UNNEST(vals) x), NULL))  AS sbp_cv6h
  FROM vitals_packed
  GROUP BY subject_id, hadm_id, stay_id
),

-- 11) Chronic conditions (from diagnoses_icd)
dx AS (
  SELECT subject_id, hadm_id, icd_code,
         CASE WHEN icd_code LIKE 'I2%' OR icd_code LIKE 'I5%' THEN 1 ELSE 0 END AS cardiovascular_dx,
         CASE WHEN icd_code LIKE 'E1%' THEN 1 ELSE 0 END AS diabetes_dx,
         CASE WHEN icd_code LIKE 'J4%' OR icd_code LIKE 'J44%' THEN 1 ELSE 0 END AS copd_dx,
         CASE WHEN icd_code LIKE 'N18%' THEN 1 ELSE 0 END AS ckd_dx
  FROM `physionet-data.mimiciv_3_1_hosp.diagnoses_icd`
),
comorbidities AS (
  SELECT subject_id, hadm_id,
         MAX(cardiovascular_dx) AS has_cardiovascular,
         MAX(diabetes_dx)       AS has_diabetes,
         MAX(copd_dx)           AS has_copd,
         MAX(ckd_dx)            AS has_ckd
  FROM dx
  GROUP BY subject_id, hadm_id
)

-- 12) Final row-per-transfer dataset
SELECT
  x.subject_id, x.hadm_id, x.stay_id, x.t0_transfer,

  -- Readmission labels
  b.next_icu_in, b.hours_to_next_icu, b.label_readmit_24h, b.label_readmit_72h,

  -- Recurrent pattern context
  b.prior_icu_bounces_in_hadm,

  -- 30-day readmission label (hadm-level)
  rf.label_readmit30_unplanned,

  -- Exposure: vasopressors & timings
  IFNULL(p.any_presser_6h, FALSE) AS any_presser_6h,
  TIMESTAMP_DIFF(x.t0_transfer, lp.last_presser_end, HOUR)   AS hrs_since_presser_off,

  -- Extubation timing
  TIMESTAMP_DIFF(x.t0_transfer, le.last_extubation_time, HOUR) AS hrs_since_extubation,

  -- Vitals features (incl. SBP)
  vf.hr_last, vf.rr_last, vf.map_last, vf.sbp_last,
  vf.hr_cv6h, vf.rr_cv6h, vf.map_cv6h, vf.sbp_cv6h,

  -- Demographics
  pi.gender,
  SAFE_CAST(pi.anchor_age AS INT64) + (EXTRACT(YEAR FROM x.t0_transfer) - pi.anchor_year) AS age_at_transfer,
  pi.language, pi.marital_status, pi.insurance,

  -- ICU LOS
  s.icu_los_hours,

  -- Discharge timing features
  EXTRACT(HOUR FROM x.t0_transfer) AS discharge_hour,
  EXTRACT(DAYOFWEEK FROM x.t0_transfer) AS discharge_dow,
  CASE WHEN EXTRACT(HOUR FROM x.t0_transfer) >= 17 THEN 1 ELSE 0 END AS discharge_after_5pm,
  CASE WHEN EXTRACT(DAYOFWEEK FROM x.t0_transfer) IN (1,7) THEN 1 ELSE 0 END AS discharge_weekend,

  -- Chronic conditions
  c.has_cardiovascular, c.has_diabetes, c.has_copd, c.has_ckd,

  -- Destination (sanity checks / subgroup analysis)
  x.first_careunit_after_icu

FROM icu_to_floor x
JOIN icu_stays s
  ON s.subject_id = x.subject_id AND s.hadm_id = x.hadm_id AND s.stay_id = x.stay_id
LEFT JOIN bounce_labels b
  ON b.subject_id = x.subject_id AND b.hadm_id = x.hadm_id AND b.stay_id = x.stay_id AND b.t0_transfer = x.t0_transfer
LEFT JOIN readmit_flags rf
  ON rf.subject_id = x.subject_id AND rf.hadm_id = x.hadm_id
JOIN patient_info pi
  ON pi.subject_id = x.subject_id AND pi.hadm_id = x.hadm_id
LEFT JOIN vitals_features vf
  ON vf.subject_id = x.subject_id AND vf.hadm_id = x.hadm_id AND vf.stay_id = x.stay_id
LEFT JOIN pressor_last6h p
  ON p.subject_id = x.subject_id AND p.hadm_id = x.hadm_id AND p.stay_id = x.stay_id AND p.t0_transfer = x.t0_transfer
LEFT JOIN last_presser_off lp
  ON lp.subject_id = x.subject_id AND lp.hadm_id = x.hadm_id AND lp.stay_id = x.stay_id AND lp.t0_transfer = x.t0_transfer
LEFT JOIN last_extubation le
  ON le.subject_id = x.subject_id AND le.hadm_id = x.hadm_id AND le.stay_id = x.stay_id AND le.t0_transfer = x.t0_transfer
LEFT JOIN comorbidities c
  ON c.subject_id = x.subject_id AND c.hadm_id = x.hadm_id

ORDER BY x.subject_id, x.hadm_id, x.t0_transfer;
"""


df = bq_to_df_safe(sql)
print(f"Rows fetched: {len(df):,}")
df.head()

"""### Subtask:
Define the `bq_to_df_safe` function. This function will encapsulate the logic for querying BigQuery using `pandas_gbq.read_gbq`, including the necessary billing project ID and disabling the BigQuery Storage API to avoid permission issues.
"""

def bq_to_df_safe(sql_query):
    """
    Executes a BigQuery SQL query and returns the result as a pandas DataFrame.
    Disables the BigQuery Storage API to avoid 'bigquery.readsessions.create' permission errors.
    """
    try:
        # Ensure BILLING_PROJECT_ID is defined globally or passed if needed
        # For this context, it's assumed BILLING_PROJECT_ID is accessible.
        df = pandas_gbq.read_gbq(sql_query, project_id=BILLING_PROJECT_ID, use_bqstorage_api=False)
        return df
    except Exception as e:
        print(f"Error querying BigQuery: {e}")
        print("Please ensure your BILLING_PROJECT_ID is correct and has billing enabled, and that you have permission to query BigQuery.")
        return None

print("bq_to_df_safe function defined successfully.")

"""# Task
Define the `bq_to_df_safe` function that queries BigQuery using `pandas_gbq.read_gbq`, explicitly disabling the BigQuery Storage API, and confirm that the function is defined and ready for use.

## Define bq_to_df_safe Function

### Subtask:
Define the `bq_to_df_safe` function. This function will encapsulate the logic for querying BigQuery using `pandas_gbq.read_gbq`, including the necessary billing project ID and disabling the BigQuery Storage API to avoid permission issues.

**Reasoning**:
To define the `bq_to_df_safe` function, I will create a Python function that encapsulates the BigQuery query logic, including error handling and explicit use of `pandas_gbq.read_gbq` with the specified parameters to avoid `bigquery.readsessions.create` permission issues.
"""

def bq_to_df_safe(sql_query):
    """
    Executes a BigQuery SQL query and returns the result as a pandas DataFrame.
    Disables the BigQuery Storage API to avoid 'bigquery.readsessions.create' permission errors.
    """
    try:
        # Ensure BILLING_PROJECT_ID is defined globally or passed if needed
        # For this context, it's assumed BILLING_PROJECT_ID is accessible.
        df = pandas_gbq.read_gbq(sql_query, project_id=BILLING_PROJECT_ID, use_bqstorage_api=False)
        return df
    except Exception as e:
        print(f"Error querying BigQuery: {e}")
        print("Please ensure your BILLING_PROJECT_ID is correct and has billing enabled, and that you have permission to query BigQuery.")
        return None

print("bq_to_df_safe function defined successfully.")

df["any_presser_6h"] = df["any_presser_6h"].astype(int)

# ================================================
# 🧠 Exploratory Data Analysis (EDA)
#     ICU Readmission Risk — 24h vs 72h (incl. SBP)
# ================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

eda = df.copy()

# =====================================================
# 1️⃣ Structure + Missing Values
# =====================================================
print("Shape:", eda.shape)
print("\nColumns:\n", eda.columns.tolist())

print("\nMissing values (%):")
print((eda.isna().mean() * 100).round(1).sort_values(ascending=False).head(20))

# =====================================================
# 2️⃣ Outcome Distributions
# =====================================================
targets = ['label_readmit_24h', 'label_readmit_72h']
available_targets = [c for c in targets if c in eda.columns]

for col in available_targets:
    print(f"\n{col}:")
    print(eda[col].value_counts(normalize=True).mul(100).round(1))

# Compare side by side
plt.figure(figsize=(6,4))
sns.barplot(
    data=pd.melt(eda[available_targets]),
    x='variable', y='value', estimator=np.mean, errorbar=None,
    palette='mako'
)
plt.title('Average Readmission Labels — 24h vs 72h')
plt.ylabel('Readmission Rate')
plt.xlabel('')
plt.show()

# =====================================================
# 3️⃣ Vasopressor exposure vs readmission
# =====================================================
if 'any_presser_6h' in eda.columns and available_targets:
    fig, axes = plt.subplots(1, len(available_targets), figsize=(5*len(available_targets), 4))
    if len(available_targets) == 1:
        axes = [axes]
    for i, label in enumerate(available_targets):
        sns.barplot(
            x='any_presser_6h', y=label, data=eda,
            estimator=np.mean, errorbar=None, palette='crest', ax=axes[i]
        )
        axes[i].set_title(f'{label} vs Vasopressor Use (last 6h)')
        axes[i].set_xlabel('Vasopressor use (1=Yes)')
        axes[i].set_ylabel('Readmission Rate')
    plt.tight_layout()
    plt.show()

# =====================================================
# 4️⃣ Vital Sign Instability — boxplots (HR/RR/MAP/SBP)
# =====================================================
vital_cv = [c for c in ['hr_cv6h','rr_cv6h','map_cv6h','sbp_cv6h'] if c in eda.columns]

if available_targets and vital_cv:
    ncols = len(vital_cv)
    fig, axes = plt.subplots(len(available_targets), ncols, figsize=(4.2*ncols, 4*len(available_targets)))
    if len(available_targets) == 1:
        axes = np.array([axes])
    if ncols == 1:
        axes = axes.reshape(len(available_targets), 1)
    for row, label in enumerate(available_targets):
        for col, var in enumerate(vital_cv):
            sns.boxplot(
                data=eda, x=label, y=var,
                palette='vlag', showfliers=False, ax=axes[row, col]
            )
            axes[row, col].set_title(f'{var} vs {label}')
            axes[row, col].set_xlabel('')
    plt.suptitle('Vital Sign Variability (CV over last 6h) vs Readmission Window', fontsize=14)
    plt.tight_layout(rect=[0, 0, 1, 0.96])
    plt.show()

# =====================================================
# 5️⃣ Demographic Disparities
# =====================================================
if 'insurance' in eda.columns and available_targets:
    fig, axes = plt.subplots(1, len(available_targets), figsize=(5*len(available_targets), 4))
    if len(available_targets) == 1:
        axes = [axes]
    for i, label in enumerate(available_targets):
        readmit_by_ins = eda.groupby('insurance')[label].mean().sort_values(ascending=False)
        sns.barplot(x=readmit_by_ins.index, y=readmit_by_ins.values, palette='crest', ax=axes[i])
        axes[i].set_xticklabels(readmit_by_ins.index, rotation=45, ha='right')
        axes[i].set_title(f'{label} by Insurance Type')
        axes[i].set_ylabel('Readmission Rate')
    plt.tight_layout()
    plt.show()

if 'gender' in eda.columns and available_targets:
    fig, axes = plt.subplots(1, len(available_targets), figsize=(4.5*len(available_targets), 3.5))
    if len(available_targets) == 1:
        axes = [axes]
    for i, label in enumerate(available_targets):
        readmit_by_gender = eda.groupby('gender')[label].mean()
        sns.barplot(x=readmit_by_gender.index, y=readmit_by_gender.values, palette='pastel', ax=axes[i])
        axes[i].set_title(f'{label} by Gender')
        axes[i].set_ylabel('Rate')
    plt.tight_layout()
    plt.show()

# =====================================================
# 6️⃣ Correlation Heatmap (recomputed; includes SBP)
# =====================================================
num_cols = eda.select_dtypes(include=[np.number]).columns.tolist()
drop_cols = ['subject_id','hadm_id','stay_id']
num_cols = [c for c in num_cols if c not in drop_cols]
corr = eda[num_cols].corr()

plt.figure(figsize=(14,10))
sns.heatmap(
    corr,
    cmap='coolwarm',
    annot=True,
    fmt=".2f",
    annot_kws={"size":8},
    cbar_kws={'shrink':0.8},
    center=0,
    linewidths=0.4
)
plt.title('Correlation Heatmap (with Values)', fontsize=15)
plt.tight_layout()
plt.show()

# =====================================================
# 7️⃣ Distributions of Core Continuous Features
# =====================================================
features = [c for c in ['age_at_transfer','icu_los_hours','hrs_since_presser_off','hrs_since_extubation'] if c in eda.columns]
if features:
    eda[features].hist(bins=30, figsize=(12,6), color='skyblue', edgecolor='black')
    plt.suptitle('Distribution of Key Continuous Variables')
    plt.show()

# =====================================================
# 8️⃣ Summary Statistics (incl. SBP CV)
# =====================================================
summary_cols = features + vital_cv
if summary_cols:
    print("\nDescriptive Statistics (Continuous Variables):\n")
    print(eda[summary_cols].describe().T)

# =====================================================
# 9️⃣ Automated Insights (now also mention SBP)
# =====================================================
for label in available_targets:
    readmit_rate = eda[label].mean() * 100
    pressor_rate = eda['any_presser_6h'].mean() * 100 if 'any_presser_6h' in eda.columns else np.nan
    avg_cv_map = eda['map_cv6h'].mean() if 'map_cv6h' in eda.columns else np.nan
    avg_cv_sbp = eda['sbp_cv6h'].mean() if 'sbp_cv6h' in eda.columns else np.nan
    print(f"\n🧠 Insights for {label}:")
    print(f"• Readmission rate: {readmit_rate:.1f}%")
    print(f"• % transferred on vasopressors (last 6h): {pressor_rate:.1f}%")
    print(f"• Avg MAP variability: {avg_cv_map:.2f}")
    if not np.isnan(avg_cv_sbp):
        print(f"• Avg SBP variability: {avg_cv_sbp:.2f}")
    print(f"• Median ICU LOS: {eda['icu_los_hours'].median():.1f} h" if 'icu_los_hours' in eda.columns else "• ICU LOS not available")
    if 'any_presser_6h' in eda.columns:
        corr_presser_24 = eda[['any_presser_6h', 'label_readmit_24h']].corr().iloc[0,1] if 'label_readmit_24h' in eda.columns else np.nan
        corr_presser_72 = eda[['any_presser_6h', 'label_readmit_72h']].corr().iloc[0,1] if 'label_readmit_72h' in eda.columns else np.nan
        if not np.isnan(corr_presser_24):
            print(f"• Corr(presser ↔ 24h) = {corr_presser_24:.2f}")
        if not np.isnan(corr_presser_72):
            print(f"• Corr(presser ↔ 72h) = {corr_presser_72:.2f}")
    print("• RR_CV6h and SBP_CV6h show instability signals among readmits" if 'sbp_cv6h' in eda.columns else "• RR_CV6h shows instability signal among readmits")

# ================================================
# 📊 Vital Sign Variability — ICU Stability Analysis
# ================================================
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import textwrap

# Focus on key variables
vital_cv = ['hr_cv6h', 'rr_cv6h', 'map_cv6h']
titles = {
    'hr_cv6h': 'Heart Rate Variability (CV, last 6h)',
    'rr_cv6h': 'Respiratory Rate Variability (CV, last 6h)',
    'map_cv6h': 'MAP Variability (CV, last 6h)'
}

plt.figure(figsize=(14,5))
for i, var in enumerate(vital_cv):
    if var in df.columns:
        plt.subplot(1, 3, i+1)
        sns.boxplot(
            data=df, x='label_readmit_24h', y=var,
            palette='vlag', showfliers=False
        )
        plt.title(titles[var], fontsize=13, weight='bold')
        plt.xlabel('Readmitted ≤24h (1=Yes, 0=No)')
        plt.ylabel('Coefficient of Variation')
plt.suptitle('Vital Sign Variability in Last 6h Before ICU Discharge', fontsize=15, weight='bold')
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

# ================================================
# 📋 Vital Sign Variability Summary Table (by Readmission Status)
# ================================================
import pandas as pd
import numpy as np
from scipy import stats

# Focus on key variability features
vital_cv = ['hr_cv6h', 'rr_cv6h', 'map_cv6h']
labels = {0: 'No Readmission ≤24h', 1: 'Readmitted ≤24h'}

summary_rows = []

for var in vital_cv:
    if var in df.columns:
        # Split data into two groups
        grp0 = df.loc[df['label_readmit_24h'] == 0, var].dropna()
        grp1 = df.loc[df['label_readmit_24h'] == 1, var].dropna()

        # Compute group-level summary
        med0, med1 = np.median(grp0), np.median(grp1)
        mean0, mean1 = np.mean(grp0), np.mean(grp1)
        std0, std1 = np.std(grp0), np.std(grp1)

        # Mann-Whitney U Test (non-parametric)
        u_stat, p_val = stats.mannwhitneyu(grp0, grp1, alternative='two-sided')

        summary_rows.append({
            'Vital Sign Variability': var,
            'Median (No Readmit)': round(med0, 3),
            'Median (Readmit ≤24h)': round(med1, 3),
            'Mean Difference': round(mean1 - mean0, 3),
            'p-value': f"{p_val:.4f}",
            'Interpretation': (
                "Higher in readmitted group → instability"
                if mean1 > mean0 else "Lower in readmitted group → stable"
            )
        })

# Create summary table
vital_summary = pd.DataFrame(summary_rows)
vital_summary.style.background_gradient(subset=['Mean Difference'], cmap='coolwarm', axis=None)\
              .set_caption("Vital Sign Variability (CV) — Comparison by 24h Readmission Status")

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# ✅ Select only numeric columns
numeric_df = df.select_dtypes(include=[np.number])

# Drop identifiers (they’ll just clutter the matrix)
drop_cols = ['subject_id', 'hadm_id', 'stay_id']
numeric_df = numeric_df.drop(columns=[c for c in drop_cols if c in numeric_df.columns], errors='ignore')

# 🧮 Compute Pearson correlation
corr = numeric_df.corr(method='pearson')

# 🎨 Plot annotated heatmap
plt.figure(figsize=(14, 10))
sns.heatmap(
    corr,
    cmap='coolwarm',
    center=0,
    annot=True,         # ✅ shows numeric correlation values
    fmt=".2f",          # 2 decimal precision
    linewidths=0.5,
    cbar_kws={'label': 'Correlation coefficient (r)'}
)
plt.title('Correlation Heatmap — ICU-to-Floor Logistic Regression Features', fontsize=16, weight='bold')
plt.tight_layout()
plt.show()

# ================================================
# 🧠 Logistic Regression — ICU Readmission (≤24h) with dtype fix
# ================================================
import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler

# -------------------------------
# 1️⃣ Select core and categorical features
# -------------------------------
core_features = [
    'any_presser_6h',
    'hr_cv6h', 'rr_cv6h', 'map_cv6h',
    'hrs_since_presser_off', 'hrs_since_extubation',
    'icu_los_hours', 'age_at_transfer',
    'prior_icu_bounces_in_hadm'
]
cat_features = ['gender', 'insurance', 'marital_status', 'language']

df_model = df.copy()

# Target must exist
df_model = df_model[df_model['label_readmit_24h'].notna()]
y = df_model['label_readmit_24h'].astype(int)

# -------------------------------
# 2️⃣ Handle missing values
# -------------------------------
for col in core_features:
    if col in df_model.columns:
        df_model[col] = df_model[col].fillna(df_model[col].median())

for col in cat_features:
    if col in df_model.columns:
        df_model[col] = df_model[col].fillna(df_model[col].mode()[0])

# -------------------------------
# 3️⃣ Prepare X
# -------------------------------
X = df_model[core_features + cat_features].copy()

# Convert categorical to dummy variables
X = pd.get_dummies(X, columns=cat_features, drop_first=True)

# Convert all to numeric (forces dtype to float)
X = X.apply(pd.to_numeric, errors='coerce')

# Fill any remaining NaNs with 0
X = X.fillna(0)

# -------------------------------
# 4️⃣ Scale numeric columns
# -------------------------------
scaler = StandardScaler()
num_cols = [c for c in core_features if c in X.columns]
X[num_cols] = scaler.fit_transform(X[num_cols])

# Add intercept
X = sm.add_constant(X, has_constant='add')

# Verify all numeric
print("Dtypes check:\n", X.dtypes.value_counts())

# -------------------------------
# 5️⃣ Fit logistic regression
# -------------------------------
model = sm.Logit(y, X.astype(float))
result = model.fit(disp=0)

# -------------------------------
# 6️⃣ Summarize Odds Ratios
# -------------------------------
params = result.params
conf = result.conf_int()
odds = np.exp(params)
ci_lower = np.exp(conf[0])
ci_upper = np.exp(conf[1])

summary_table = pd.DataFrame({
    'Feature': params.index,
    'Odds Ratio': odds,
    'CI Lower': ci_lower,
    'CI Upper': ci_upper,
    'p-value': result.pvalues
}).sort_values(by='Odds Ratio', ascending=False)

print("\n✅ Logistic Regression Completed Successfully")
display(summary_table.style.background_gradient(subset=['Odds Ratio'], cmap='coolwarm')
        .format({'Odds Ratio': '{:.2f}', 'CI Lower': '{:.2f}', 'CI Upper': '{:.2f}', 'p-value': '{:.4f}'}))

# ================================================
# 🎯 Significant Predictors Plot — ICU Readmission Model
# ================================================
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Make sure your regression summary table is named `summary_table`
# and has columns: 'Feature', 'Odds Ratio', 'CI Lower', 'CI Upper', 'p-value'

# ------------------------------------------
# 1️⃣ Filter for statistically significant variables
# ------------------------------------------
sig_vars = summary_table[summary_table['p-value'] < 0.05].copy()

if sig_vars.empty:
    print("⚠️ No variables with p < 0.05 found. Try relaxing threshold or recheck data.")
else:
    # Sort by Odds Ratio for readability
    sig_vars = sig_vars.sort_values(by='Odds Ratio', ascending=False)

    # ------------------------------------------
    # 2️⃣ Plot Odds Ratios with Confidence Intervals
    # ------------------------------------------
    plt.figure(figsize=(8, max(4, 0.5 * len(sig_vars))))
    sns.set(style="whitegrid")

    # Error bars = 95% CI
    plt.errorbar(
        x=sig_vars['Odds Ratio'],
        y=sig_vars['Feature'],
        xerr=[
            sig_vars['Odds Ratio'] - sig_vars['CI Lower'],
            sig_vars['CI Upper'] - sig_vars['Odds Ratio']
        ],
        fmt='o', color='steelblue', ecolor='gray', elinewidth=2, capsize=4
    )

    plt.axvline(1, color='red', linestyle='--', lw=1.5, label='No Effect (OR = 1)')
    plt.title('Significant Predictors of ICU Readmission (≤24 h)', fontsize=14, weight='bold')
    plt.xlabel('Odds Ratio (log scale)')
    plt.xscale('log')
    plt.legend(loc='lower right')
    plt.tight_layout()
    plt.show()

    # ------------------------------------------
    # 3️⃣ Textual Summary
    # ------------------------------------------
    print("\n🩺 **Interpretation of Significant Predictors:**")
    for _, row in sig_vars.iterrows():
        direction = "↑ Increased risk" if row['Odds Ratio'] > 1 else "↓ Protective effect"
        print(f"• {row['Feature']}: OR ={row['Odds Ratio']:.2f} "
              f"(95% CI {row['CI Lower']:.2f}–{row['CI Upper']:.2f}), "
              f"p = {row['p-value']:.4f} → {direction}")

# ================================================
# Safe ROC/AUC + Significant Predictors + Narrative
# (no .predict(X); uses model.exog / endog directly)
# ================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, roc_auc_score
from scipy.special import expit  # logistic/sigmoid

# --- 0) Pull design matrix and target used in fitting ---
exog = np.asarray(result.model.exog, dtype="float64")               # design matrix used in fit
exog_names = list(result.model.exog_names)                          # column names incl. 'const'
endog = np.asarray(result.model.endog, dtype="float64").astype(int) # y used in fit

# --- 1) Odds-ratio table (force-float everywhere) ---
params = pd.Series(result.params, index=exog_names, dtype="float64")
conf = pd.DataFrame(result.conf_int(), index=params.index, columns=["lower","upper"]).astype("float64")
pvals = pd.Series(result.pvalues, index=params.index, dtype="float64")

or_vals  = np.exp(params.values)
ci_lower = np.exp(conf["lower"].values)
ci_upper = np.exp(conf["upper"].values)

summary_table = pd.DataFrame({
    "Feature": params.index,
    "Odds Ratio": or_vals,
    "CI Lower": ci_lower,
    "CI Upper": ci_upper,
    "p-value": pvals.values
})

# --- 2) Probabilities via manual logistic (expit) ---
linpred = exog @ params.values               # linear predictor
probs = expit(linpred).astype("float64")     # predicted probabilities

# --- 3) ROC + AUC ---
fpr, tpr, thr = roc_curve(endog, probs)
auc = roc_auc_score(endog, probs)

plt.figure(figsize=(6,6))
plt.plot(fpr, tpr, lw=2, label=f"AUC = {auc:.3f}")
plt.plot([0,1],[0,1], '--', lw=1)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve — ICU Readmission (≤24h)')
plt.legend(loc='lower right')
plt.tight_layout()
plt.show()

print(f"AUC = {auc:.3f}")

# --- 4) Plot only significant predictors (p < 0.05) ---
sig = summary_table[summary_table["p-value"] < 0.05].copy()
if sig.empty:
    print("⚠️ No variables with p < 0.05 to plot.")
else:
    sig = sig.sort_values("Odds Ratio", ascending=True)
    x  = sig["Odds Ratio"].to_numpy(dtype="float64")
    lo = sig["CI Lower"].to_numpy(dtype="float64")
    hi = sig["CI Upper"].to_numpy(dtype="float64")
    y_pos = np.arange(len(sig))

    plt.figure(figsize=(8, max(3, 0.5*len(sig))))
    left_err  = x - lo
    right_err = hi - x
    plt.errorbar(x, y_pos, xerr=[left_err, right_err], fmt='o', capsize=4, lw=1.8)
    plt.axvline(1.0, linestyle='--', lw=1)
    plt.yticks(y_pos, sig["Feature"])
    plt.xscale('log')
    plt.xlabel('Odds Ratio (log scale)')
    plt.title('Significant Predictors (p < 0.05) — ICU Readmission ≤24h')
    plt.tight_layout()
    plt.show()

# --- 5) Auto-narrative (top 5 by |OR-1| among significant; else by p-value) ---
if not sig.empty:
    top = sig.assign(Impact=np.abs(sig["Odds Ratio"] - 1.0))\
             .sort_values("Impact", ascending=False).head(5)
else:
    top = summary_table.sort_values("p-value").head(5)

auc_txt = ("excellent" if auc >= 0.85 else
           "good"      if auc >= 0.75 else
           "moderate"  if auc >= 0.65 else
           "limited")

print("\n📊 Model Performance Summary")
print(f"AUC = {auc:.3f} → The model shows {auc_txt} discriminative power.\n")

print("🩺 Key Predictors — Slide-Ready Narrative:")
for _, r in top.iterrows():
    direction = "increases" if r["Odds Ratio"] > 1 else "is associated with lower"
    pct = (abs(r["Odds Ratio"] - 1.0) * 100.0)
    print(f"• {r['Feature']}: OR {r['Odds Ratio']:.2f} "
          f"(95% CI {r['CI Lower']:.2f}–{r['CI Upper']:.2f}, p={r['p-value']:.4f}) — "
          f"each unit change {direction} odds by ~{pct:.1f}%.")

# ================================================
# 📏 Confusion Matrix + Accuracy + FP-focused metrics
# Requires:
#   endog : 1-D array of true labels (0/1)
#   probs : 1-D array of predicted probabilities from the model
# ================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import (
    confusion_matrix, accuracy_score, precision_score, recall_score,
    f1_score, roc_curve
)

def metrics_at_threshold(y_true, y_prob, thr: float) -> dict:
    y_pred = (y_prob >= thr).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, zero_division=0)      # PPV
    rec = recall_score(y_true, y_pred)                           # Sensitivity/TPR
    f1 = f1_score(y_true, y_pred)
    # Specificity (TNR) and NPV
    tnr = tn / (tn + fp) if (tn + fp) > 0 else np.nan
    npv = tn / (tn + fn) if (tn + fn) > 0 else np.nan
    fpr = fp / (fp + tn) if (fp + tn) > 0 else np.nan
    return {
        "threshold": thr, "TP": tp, "FP": fp, "FN": fn, "TN": tn,
        "Accuracy": acc, "Precision(PPV)": prec, "Recall(Sensitivity)": rec,
        "Specificity(TNR)": tnr, "F1": f1, "NPV": npv, "FPR": fpr
    }

y_true = np.asarray(endog).astype(int)
y_prob = np.asarray(probs).astype(float)

# 1) Baseline metrics at threshold = 0.50
m_050 = metrics_at_threshold(y_true, y_prob, 0.50)

# 2) Youden's J best threshold (maximizes Sensitivity+Specificity-1) — balanced tradeoff
fpr, tpr, thr = roc_curve(y_true, y_prob)
youden_idx = np.argmax(tpr - fpr)
thr_youden = thr[youden_idx]
m_youden = metrics_at_threshold(y_true, y_prob, thr_youden)

# 3) FP-conservative threshold: choose highest threshold with FPR ≤ 0.10 (10%) and best precision
#    (Adjust the FPR cap to your tolerance, e.g., 0.05 for very strict.)
candidates = []
for th in np.linspace(0.01, 0.99, 99):
    m = metrics_at_threshold(y_true, y_prob, th)
    if np.isfinite(m["FPR"]) and m["FPR"] <= 0.10:
        candidates.append(m)
if candidates:
    # Maximize precision among FP-constrained candidates; tie-break by recall
    m_fp_cons = sorted(candidates, key=lambda x: (x["Precision(PPV)"], x["Recall(Sensitivity)"]), reverse=True)[0]
else:
    # fallback: just use 0.5 if nothing hits the FPR cap
    m_fp_cons = m_050

# ---- Summarize
summary = pd.DataFrame([m_050, m_youden, m_fp_cons])
summary["Setting"] = ["Threshold 0.50", f"Youden J ({thr_youden:.2f})", f"FP≤10% ({m_fp_cons['threshold']:.2f})"]
cols = ["Setting","threshold","TP","FP","FN","TN","Accuracy","Precision(PPV)","Recall(Sensitivity)","Specificity(TNR)","F1","NPV","FPR"]
summary = summary[cols]
print("📊 Threshold comparison (focus on FP control):")
display(summary.style.format({
    "threshold": "{:.2f}", "Accuracy": "{:.3f}", "Precision(PPV)": "{:.3f}",
    "Recall(Sensitivity)": "{:.3f}", "Specificity(TNR)": "{:.3f}", "F1": "{:.3f}",
    "NPV": "{:.3f}", "FPR": "{:.3f}"
}))

# ---- Confusion matrix plot for FP-conservative choice
best = m_fp_cons
y_pred_best = (y_prob >= best["threshold"]).astype(int)
cm = confusion_matrix(y_true, y_pred_best)

plt.figure(figsize=(4.5,4))
plt.imshow(cm, cmap="RdYlBu")
plt.title(f"Confusion Matrix (FP≤10% @ thr={best['threshold']:.2f})")
plt.xticks([0,1], ["Pred 0","Pred 1"])
plt.yticks([0,1], ["True 0","True 1"])
for (i,j), val in np.ndenumerate(cm):
    plt.text(j, i, f"{val}", ha="center", va="center", fontsize=12)
plt.colorbar(fraction=0.046, pad=0.04)
plt.tight_layout()
plt.show()

print("🧠 Interpretation:")
print(f"- Using thr={best['threshold']:.2f}, FPR={best['FPR']:.3f} (false-positive rate) is controlled ≤ 0.10.")
print(f"- Precision(PPV)={best['Precision(PPV)']:.3f}: among flagged patients, this proportion truly bounce.")
print(f"- Recall(Sensitivity)={best['Recall(Sensitivity)']:.3f}: fraction of true bounces we catch.")
print(f"- Specificity={best['Specificity(TNR)']:.3f}: fraction of stable patients correctly not flagged.")

# ================================================
# Confusion Matrix with Counts — ICU Readmission Model
# ================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# --- Step 1️⃣: Prepare inputs ---
# y_true: actual labels (0/1)
# y_prob: predicted probabilities (from model)
# Use threshold = 0.5 (you can change it as per FP/Recall focus)
threshold = 0.2
y_pred = (y_prob >= threshold).astype(int)

# --- Step 2️⃣: Compute confusion matrix ---
cm = confusion_matrix(y_true, y_pred)
cm_df = pd.DataFrame(cm,
                     index=["Actual: Stable (0)", "Actual: Readmit (1)"],
                     columns=["Pred: Stable (0)", "Pred: Readmit (1)"])

# --- Step 3️⃣: Plot the confusion matrix ---
plt.figure(figsize=(6,5))
sns.heatmap(cm_df, annot=True, fmt='d', cmap='Blues', cbar=False,
            annot_kws={"size": 16, "weight": "bold"})
plt.title(f"Confusion Matrix (Threshold = {threshold:.2f})", fontsize=14, weight='bold')
plt.xlabel("Model Prediction", fontsize=12)
plt.ylabel("Actual Outcome", fontsize=12)
plt.tight_layout()
plt.show()

# --- Step 4️⃣: Print quick summary ---
tn, fp, fn, tp = cm.ravel()
print(f"✅ Confusion Matrix (Threshold={threshold:.2f})")
print(f"True Positives (TP):  {tp}")
print(f"False Positives (FP): {fp}")
print(f"False Negatives (FN): {fn}")
print(f"True Negatives (TN):  {tn}")
print(f"Accuracy:  {(tp+tn)/(tp+tn+fp+fn):.3f}")
print(f"Precision: {tp/(tp+fp):.3f}")
print(f"Recall:    {tp/(tp+fn):.3f}")

import numpy as np
import pandas as pd

np.random.seed(42)

# 1000 mock ICU patients
n = 1000
df = pd.DataFrame({
    'any_presser_6h': np.random.binomial(1, 0.1, n),
    'hr_cv6h': np.random.normal(0.08, 0.03, n),
    'rr_cv6h': np.random.normal(0.15, 0.05, n),
    'map_cv6h': np.random.normal(0.09, 0.04, n),
    'hrs_since_presser_off': np.random.normal(10, 5, n),
    'hrs_since_extubation': np.random.normal(8, 4, n),
    'icu_los_hours': np.random.normal(120, 50, n),
    'age_at_transfer': np.random.normal(65, 12, n),
    'prior_icu_bounces_in_hadm': np.random.poisson(0.2, n),
    'gender': np.random.choice(['M','F'], n),
    'insurance': np.random.choice(['Medicare','Private','Other'], n),
    'marital_status': np.random.choice(['Married','Single','Divorced'], n),
    'language': np.random.choice(['English','Arabic','Hindi','Other'], n),
    # simulate rare positives (6%)
    'label_readmit_24h': np.random.binomial(1, 0.06, n)
})

print(f"✅ Dummy dataset ready: {df.shape}")
print(df['label_readmit_24h'].value_counts(normalize=True))

# =====================================================
# 1️⃣ Re-load dataset into `data`
#     (Replace `df` with your cleaned ICU dataset variable)
# =====================================================

# If your data was stored earlier as `df`:
data = df.copy()

# If you saved it to CSV, uncomment below and specify your file path:
# data = pd.read_csv('/content/your_cleaned_data.csv')

# Ensure label column exists
target_col = 'label_readmit_24h'
if target_col not in data.columns:
    raise ValueError(f"❌ Column '{target_col}' not found. Please confirm your target column name.")

# =====================================================
# 2️⃣ Split features & labels
# =====================================================
numeric_cols = [
    'any_presser_6h', 'hr_cv6h', 'rr_cv6h', 'map_cv6h',
    'hrs_since_presser_off', 'hrs_since_extubation',
    'icu_los_hours', 'age_at_transfer', 'prior_icu_bounces_in_hadm'
]
categorical_cols = ['gender', 'insurance', 'marital_status', 'language']

# Keep only available columns
numeric_cols = [c for c in numeric_cols if c in data.columns]
categorical_cols = [c for c in categorical_cols if c in data.columns]

X = data[numeric_cols + categorical_cols]
y = data[target_col].astype(int)

# =====================================================
# 3️⃣ Fit model again (if not already done)
# =====================================================
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

numeric_pipe = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_pipe = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('ohe', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

pre = ColumnTransformer(
    transformers=[
        ('num', numeric_pipe, numeric_cols),
        ('cat', categorical_pipe, categorical_cols)
    ],
    remainder='drop'
)

pipe = Pipeline(steps=[
    ('pre', pre),
    ('clf', LogisticRegression(class_weight='balanced', solver='liblinear', max_iter=1000, random_state=42))
])

pipe.fit(X, y)

# =====================================================
# 4️⃣ Define y_true and y_prob for evaluation
# =====================================================
y_true = y.to_numpy()
y_prob = pipe.predict_proba(X)[:, 1]

print(f"✅ Data, model, and predictions ready — {len(y_true)} patients processed.")

# ================================================
# ⚖️ Logistic Regression with Class Weighting (Imbalance-aware)
# - Robust pipeline: Impute ➜ Scale ➜ One-hot ➜ LogisticRegression(class_weight='balanced')
# - Outputs: Odds Ratios, ROC/AUC, PR/AUC, Confusion Matrix at chosen threshold
# ================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    roc_auc_score, roc_curve, precision_recall_curve, average_precision_score,
    confusion_matrix, precision_score, recall_score, accuracy_score, f1_score
)

# -------------------------------
# 1) Define features & target
# -------------------------------
target_col = 'label_readmit_24h'
numeric_cols = [
    'any_presser_6h',               # binary, treat as numeric is fine
    'hr_cv6h','rr_cv6h','map_cv6h',
    'hrs_since_presser_off','hrs_since_extubation',
    'icu_los_hours','age_at_transfer',
    'prior_icu_bounces_in_hadm'
]
categorical_cols = ['gender','insurance','marital_status','language']

# Keep rows with target present
data = df.copy()
data = data[data[target_col].notna()]
y = data[target_col].astype(int)

# Keep only existing columns (in case some are missing in your df)
numeric_cols = [c for c in numeric_cols if c in data.columns]
categorical_cols = [c for c in categorical_cols if c in data.columns]

# -------------------------------
# 2) Preprocess + Model pipeline
# -------------------------------
numeric_pipe = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_pipe = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('ohe', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

pre = ColumnTransformer(
    transformers=[
        ('num', numeric_pipe, numeric_cols),
        ('cat', categorical_pipe, categorical_cols)
    ],
    remainder='drop'
)

# Class weighting directly addresses 6% positive prevalence
logreg = LogisticRegression(
    class_weight='balanced',
    solver='liblinear',  # good for small/medium; use 'saga' for L1/L2 elastic-net
    max_iter=1000,
    random_state=42
)

pipe = Pipeline(steps=[('pre', pre), ('clf', logreg)])

# -------------------------------
# 3) Fit
# -------------------------------
X = data[numeric_cols + categorical_cols]
pipe.fit(X, y)

# -------------------------------
# 4) Odds Ratios (from scikit-learn coefficients)
# -------------------------------
# Get feature names after preprocessing
cat_feature_names = []
if categorical_cols:
    ohe = pipe.named_steps['pre'].named_transformers_['cat'].named_steps['ohe']
    cat_feature_names = ohe.get_feature_names_out(categorical_cols).tolist()

feature_names = numeric_cols + cat_feature_names
coefs = pipe.named_steps['clf'].coef_.ravel()  # shape (1, n_features)
odds_ratios = np.exp(coefs)

or_table = pd.DataFrame({
    'Feature': feature_names,
    'Odds Ratio': odds_ratios
}).sort_values('Odds Ratio', ascending=False)

print("🔎 Top Odds Ratios (unadjusted CI not shown in sklearn):")
display(or_table.head(15))

# -------------------------------
# 5) Discrimination: ROC / PR
# -------------------------------
y_prob = pipe.predict_proba(X)[:, 1]
auc = roc_auc_score(y, y_prob)
ap = average_precision_score(y, y_prob)  # AUC-PR (better for rare positives)

# ROC curve
fpr, tpr, thr_roc = roc_curve(y, y_prob)
plt.figure(figsize=(6,6))
plt.plot(fpr, tpr, label=f'AUC = {auc:.3f}')
plt.plot([0,1],[0,1],'--', lw=1)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC — ICU Readmission (≤24h)')
plt.legend(loc='lower right')
plt.tight_layout()
plt.show()

# PR curve
prec, rec, thr_pr = precision_recall_curve(y, y_prob)
plt.figure(figsize=(6,5))
plt.plot(rec, prec, lw=2)
plt.xlabel('Recall (Sensitivity)')
plt.ylabel('Precision (PPV)')
plt.title(f'Precision–Recall — AUC-PR = {ap:.3f}')
plt.tight_layout()
plt.show()

print(f"AUC (ROC)       : {auc:.3f}")
print(f"AUC-PR (avg prec): {ap:.3f}")

# -------------------------------
# 6) Confusion matrix at a safety-first threshold
#    (tune threshold to balance FP vs FN; 0.35 is a common ICU safety starting point)
# -------------------------------
threshold = 0.35
y_pred = (y_prob >= threshold).astype(int)

tn, fp, fn, tp = confusion_matrix(y, y_pred).ravel()
acc = accuracy_score(y, y_pred)
ppv = precision_score(y, y_pred, zero_division=0)    # precision
sens = recall_score(y, y_pred)                       # recall
spec = tn / (tn + fp) if (tn + fp) > 0 else np.nan
f1 = f1_score(y, y_pred)

cm = np.array([[tn, fp],[fn, tp]])
fig, ax = plt.subplots(figsize=(5.2,4.6))
im = ax.imshow(cm, cmap='Blues')
ax.set_title(f'Confusion Matrix (thr={threshold:.2f})')
ax.set_xticks([0,1]); ax.set_yticks([0,1])
ax.set_xticklabels(['Pred 0','Pred 1']); ax.set_yticklabels(['True 0','True 1'])
for (i,j), v in np.ndenumerate(cm):
    ax.text(j, i, str(v), ha='center', va='center', fontsize=14, fontweight='bold')
plt.colorbar(im, fraction=0.046, pad=0.04)
plt.tight_layout()
plt.show()

print("📊 Metrics @ threshold =", threshold)
print(f"TP={tp}  FP={fp}  FN={fn}  TN={tn}")
print(f"Accuracy : {acc:.3f}")
print(f"Precision: {ppv:.3f}   (FP control)")
print(f"Recall   : {sens:.3f}   (FN control)")
print(f"Specific.: {spec:.3f}")
print(f"F1-score : {f1:.3f}")

# -------------------------------
# 7) (Optional) FP-conservative threshold finder
#     Pick the threshold that achieves FPR ≤ 10% with best Precision
# -------------------------------
from sklearn.metrics import roc_curve
fpr_all, tpr_all, thr_all = roc_curve(y, y_prob)

candidates = []
for th in np.linspace(0.01, 0.99, 99):
    yp = (y_prob >= th).astype(int)
    tn1, fp1, fn1, tp1 = confusion_matrix(y, yp).ravel()
    fpr1 = fp1 / (fp1 + tn1) if (fp1 + tn1) > 0 else np.nan
    if np.isfinite(fpr1) and fpr1 <= 0.10:  # ≤10% FP rate among true negatives
        candidates.append({
            'thr': th,
            'precision': precision_score(y, yp, zero_division=0),
            'recall': recall_score(y, yp),
            'tn': tn1, 'fp': fp1, 'fn': fn1, 'tp': tp1
        })

if candidates:
    best = sorted(candidates, key=lambda d: (d['precision'], d['recall']), reverse=True)[0]
    print(f"\n🎯 FP-conservative choice: thr={best['thr']:.2f} (FPR≤10%)")
    print(f"TP={best['tp']} FP={best['fp']} FN={best['fn']} TN={best['tn']}")
    print(f"Precision={best['precision']:.3f}  Recall={best['recall']:.3f}")
else:
    print("\n(No threshold met the FPR≤10% constraint; consider relaxing to 15% or use Youden J.)")

# ================================================
# Threshold sweep: Precision, Recall, F1, Specificity, FPR
# ================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import (
    confusion_matrix, precision_score, recall_score, f1_score, roc_curve
)

y_true = np.asarray(y_true).astype(int)
y_prob = np.asarray(y_prob).astype(float)

def compute_metrics(y, p, thr):
    yhat = (p >= thr).astype(int)
    tn, fp, fn, tp = confusion_matrix(y, yhat).ravel()
    prec = precision_score(y, yhat, zero_division=0)
    rec  = recall_score(y, yhat)
    f1   = f1_score(y, yhat) if (prec+rec)>0 else 0.0
    spec = tn/(tn+fp) if (tn+fp)>0 else np.nan
    fpr  = fp/(fp+tn) if (fp+tn)>0 else np.nan
    return prec, rec, f1, spec, fpr

# Sweep thresholds
thr_grid = np.linspace(0.00, 1.00, 201)
rows = []
for th in thr_grid:
    prec, rec, f1, spec, fpr = compute_metrics(y_true, y_prob, th)
    rows.append((th, prec, rec, f1, spec, fpr))
sweep = pd.DataFrame(rows, columns=["threshold","precision","recall","f1","specificity","fpr"])

# Named thresholds
# 1) Youden J from ROC
fpr_roc, tpr_roc, thr_roc = roc_curve(y_true, y_prob)
youden_idx = np.argmax(tpr_roc - fpr_roc)
thr_youden = float(thr_roc[youden_idx])

# 2) Max F1
thr_max_f1 = float(sweep.iloc[sweep['f1'].idxmax()]['threshold'])

# 3) FP ≤ 10% (choose threshold with FPR<=0.10, maximize precision then recall)
fp_cap = 0.10
cands = sweep[(sweep['fpr'] <= fp_cap) & np.isfinite(sweep['fpr'])]
if len(cands):
    thr_fp10 = float(cands.sort_values(['precision','recall'], ascending=False).iloc[0]['threshold'])
else:
    thr_fp10 = None

# 4) Target Recall ≥ 0.80 (choose smallest threshold achieving it; keeps more positives)
rec_target = 0.80
cands_rec = sweep[sweep['recall'] >= rec_target]
thr_rec80 = float(cands_rec['threshold'].min()) if len(cands_rec) else None

# Plot curves
plt.figure(figsize=(9,6))
plt.plot(sweep['threshold'], sweep['precision'], label='Precision (PPV)')
plt.plot(sweep['threshold'], sweep['recall'],    label='Recall (Sensitivity)')
plt.plot(sweep['threshold'], sweep['f1'],        label='F1-score')
plt.plot(sweep['threshold'], sweep['specificity'], label='Specificity (TNR)')
plt.plot(sweep['threshold'], sweep['fpr'],         label='FPR', linestyle='--')

# Vertical markers
def vline(th, label):
    if th is not None and 0 <= th <= 1:
        plt.axvline(th, color='gray', linestyle=':', linewidth=1)
        plt.text(th, 0.02, label, rotation=90, va='bottom', ha='right', fontsize=9)

vline(thr_youden, f"Youden J ~{thr_youden:.2f}")
vline(thr_max_f1, f"Max F1 ~{thr_max_f1:.2f}")
if thr_fp10 is not None: vline(thr_fp10, f"FP≤10% ~{thr_fp10:.2f}")
if thr_rec80 is not None: vline(thr_rec80, f"Recall≥0.80 ~{thr_rec80:.2f}")

plt.ylim(0, 1.02)
plt.xlim(0, 1)
plt.xlabel('Threshold')
plt.ylabel('Metric value')
plt.title('Threshold Sweep — Precision / Recall / F1 / Specificity / FPR')
plt.legend(loc='best', ncol=2)
plt.grid(True, alpha=0.2)
plt.tight_layout()
plt.show()

# Small summary table
summary = []
def pick_row(th):
    if th is None: return None
    row = sweep.iloc[(sweep['threshold']-th).abs().idxmin()]
    return {
        "threshold": float(row['threshold']),
        "precision": float(row['precision']),
        "recall": float(row['recall']),
        "f1": float(row['f1']),
        "specificity": float(row['specificity']),
        "fpr": float(row['fpr'])
    }

summary.append(("Youden J", pick_row(thr_youden)))
summary.append(("Max F1", pick_row(thr_max_f1)))
summary.append(("FP≤10%", pick_row(thr_fp10)))
summary.append(("Recall≥0.80", pick_row(thr_rec80)))

summary_tbl = []
for name, vals in summary:
    if vals is not None:
        summary_tbl.append({"Setting": name, **vals})
summary_df = pd.DataFrame(summary_tbl)

print("📊 Key operating points:")
if len(summary_df):
    display(summary_df.style.format({
        "threshold":"{:.2f}", "precision":"{:.3f}", "recall":"{:.3f}",
        "f1":"{:.3f}", "specificity":"{:.3f}", "fpr":"{:.3f}"
    }))
else:
    print("No valid operating points computed (check inputs).")

# Quick narrative
def narr(row):
    return (f"- {row['Setting']}: thr={row['threshold']:.2f} | "
            f"Prec={row['precision']:.2f} | Rec={row['recall']:.2f} | "
            f"Spec={row['specificity']:.2f} | FPR={row['fpr']:.2f} | F1={row['f1']:.2f}")

print("\n🩺 Interpretation:")
for _, r in summary_df.iterrows():
    print(narr(r))

# ======================================================
# Side-by-side Confusion Matrices:
#   (A) Safety-first (Recall ≥ 0.80)
#   (B) FP-conservative (FPR ≤ 0.10, maximize Precision)
# Inputs expected: y_true (0/1), y_prob (predicted probabilities)
# ======================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import (
    confusion_matrix, precision_score, recall_score, f1_score,
    accuracy_score, roc_curve
)

# --- Helpers ---
def metrics_at(y_true, y_prob, thr):
    yhat = (y_prob >= thr).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, yhat).ravel()
    acc  = accuracy_score(y_true, yhat)
    prec = precision_score(y_true, yhat, zero_division=0)
    rec  = recall_score(y_true, yhat)
    f1   = f1_score(y_true, yhat)
    spec = tn / (tn + fp) if (tn + fp) > 0 else np.nan
    fpr  = fp / (fp + tn) if (fp + tn) > 0 else np.nan
    return dict(threshold=float(thr), TP=tp, FP=fp, FN=fn, TN=tn,
                Accuracy=acc, Precision=prec, Recall=rec,
                Specificity=spec, F1=f1, FPR=fpr)

def pick_thresholds(y_true, y_prob, recall_target=0.80, fpr_cap=0.10):
    # Compute ROC arrays for Youden & recall targeting
    fpr, tpr, thr = roc_curve(y_true, y_prob)

    # (A) smallest threshold achieving recall >= target
    # Note: in sklearn's roc_curve, thresholds are sorted descending.
    # We'll scan a dense grid for robustness.
    grid = np.linspace(0.0, 1.0, 2001)
    recall_arr = []
    fpr_arr    = []
    for g in grid:
        yhat = (y_prob >= g).astype(int)
        tn, fp, fn, tp = confusion_matrix(y_true, yhat).ravel()
        rec = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        fprate = fp / (fp + tn) if (fp + tn) > 0 else 0.0
        recall_arr.append(rec)
        fpr_arr.append(fprate)
    recall_arr = np.array(recall_arr)
    fpr_arr = np.array(fpr_arr)

    idx_rec = np.where(recall_arr >= recall_target)[0]
    thr_rec = float(grid[idx_rec[0]]) if len(idx_rec) else None

    # (B) FP-conservative: among thresholds with FPR ≤ cap, pick max precision (tie-break recall)
    candidates = []
    for g, fprate in zip(grid, fpr_arr):
        if np.isfinite(fprate) and fprate <= fpr_cap:
            yhat = (y_prob >= g).astype(int)
            prec = precision_score(y_true, yhat, zero_division=0)
            rec  = recall_score(y_true, yhat)
            tn, fp, fn, tp = confusion_matrix(y_true, yhat).ravel()
            candidates.append((g, prec, rec, tp, fp, fn, tn))
    if candidates:
        candidates = sorted(candidates, key=lambda t: (t[1], t[2]), reverse=True)
        thr_fp = float(candidates[0][0])
    else:
        thr_fp = None

    return thr_rec, thr_fp

# --- Prepare inputs ---
y_true = np.asarray(y_true).astype(int)
y_prob = np.asarray(y_prob).astype(float)

thr_rec80, thr_fp10 = pick_thresholds(y_true, y_prob, recall_target=0.80, fpr_cap=0.10)

# Fallbacks if constraints can’t be met
if thr_rec80 is None:
    # choose threshold maximizing recall (will be very low)
    thr_rec80 = 0.0
if thr_fp10 is None:
    # choose threshold that minimizes FPR (likely very high)
    thr_fp10 = 1.0

# Compute metrics at both thresholds
m_rec80 = metrics_at(y_true, y_prob, thr_rec80)
m_fp10  = metrics_at(y_true, y_prob, thr_fp10)

# --- Plot side-by-side confusion matrices ---
def plot_cm(ax, metrics_dict, title):
    tn, fp, fn, tp = metrics_dict["TN"], metrics_dict["FP"], metrics_dict["FN"], metrics_dict["TP"]
    cm = np.array([[tn, fp], [fn, tp]])
    im = ax.imshow(cm, cmap="Blues")
    ax.set_title(title, fontsize=12, fontweight='bold')
    ax.set_xticks([0,1]); ax.set_yticks([0,1])
    ax.set_xticklabels(['Pred 0','Pred 1']); ax.set_yticklabels(['True 0','True 1'])
    for (i,j), v in np.ndenumerate(cm):
        ax.text(j, i, str(v), ha='center', va='center', fontsize=13, fontweight='bold')
    # Metrics subtitle
    sub = (f"thr={metrics_dict['threshold']:.2f} | "
           f"Prec={metrics_dict['Precision']:.2f} | Rec={metrics_dict['Recall']:.2f} | "
           f"Spec={metrics_dict['Specificity']:.2f} | FPR={metrics_dict['FPR']:.2f}")
    ax.set_xlabel(sub, fontsize=10)

fig, axes = plt.subplots(1, 2, figsize=(10.5, 4.8))
plot_cm(axes[0], m_rec80,  "Safety-first: Recall ≥ 0.80")
plot_cm(axes[1], m_fp10,   "FP-conservative: FPR ≤ 0.10")
plt.tight_layout()
plt.show()

# --- Compact comparison table ---
comp = pd.DataFrame([m_rec80, m_fp10])
comp.insert(0, "Setting", ["Recall≥0.80", "FP≤10%"])
cols = ["Setting","threshold","TP","FP","FN","TN","Accuracy","Precision","Recall","Specificity","F1","FPR"]
comp = comp[cols]
print("📊 Operating point comparison")
display(comp.style.format({
    "threshold":"{:.2f}", "Accuracy":"{:.3f}", "Precision":"{:.3f}",
    "Recall":"{:.3f}", "Specificity":"{:.3f}", "F1":"{:.3f}", "FPR":"{:.3f}"
}))

# ======================================================
# Three-way comparison: Confusion Matrices for
#  (A) Safety-first (Recall ≥ 0.80)
#  (B) FP-conservative (FPR ≤ 0.10, best precision)
#  (C) Youden J (balanced Sensitivity/Specificity)
# Also prints a comparison table incl. Default 0.50
# ======================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import (
    confusion_matrix, precision_score, recall_score, f1_score,
    accuracy_score, roc_curve
)

# --- Ensure arrays ---
y_true = np.asarray(y_true).astype(int)
y_prob = np.asarray(y_prob).astype(float)

# --- Helpers ---
def metrics_at(y, p, thr):
    yhat = (p >= thr).astype(int)
    tn, fp, fn, tp = confusion_matrix(y, yhat).ravel()
    acc  = accuracy_score(y, yhat)
    prec = precision_score(y, yhat, zero_division=0)
    rec  = recall_score(y, yhat)
    f1   = f1_score(y, yhat) if (prec+rec)>0 else 0.0
    spec = tn/(tn+fp) if (tn+fp)>0 else np.nan
    fpr  = fp/(fp+tn) if (fp+tn)>0 else np.nan
    return dict(threshold=float(thr), TP=tp, FP=fp, FN=fn, TN=tn,
                Accuracy=acc, Precision=prec, Recall=rec,
                Specificity=spec, F1=f1, FPR=fpr)

def pick_thresholds(y, p, recall_target=0.80, fpr_cap=0.10):
    # ROC arrays for Youden J
    fpr, tpr, thr_roc = roc_curve(y, p)
    youden_idx = np.argmax(tpr - fpr)
    thr_youden = float(thr_roc[youden_idx])

    # Dense grid for recall/FPR constraints
    grid = np.linspace(0.0, 1.0, 2001)

    # (A) smallest threshold achieving recall ≥ target
    thr_rec = None
    for g in grid:  # increasing threshold reduces recall; smallest meeting target is safety-first
        yhat = (p >= g).astype(int)
        tn, fp, fn, tp = confusion_matrix(y, yhat).ravel()
        rec = tp/(tp+fn) if (tp+fn)>0 else 0.0
        if rec >= recall_target:
            thr_rec = float(g)
            break

    # (B) FP-conservative: FPR ≤ cap, maximize precision (tie-break recall)
    candidates = []
    for g in grid:
        yhat = (p >= g).astype(int)
        tn, fp, fn, tp = confusion_matrix(y, yhat).ravel()
        fprate = fp/(fp+tn) if (fp+tn)>0 else np.nan
        if np.isfinite(fprate) and fprate <= fpr_cap:
            prec = precision_score(y, yhat, zero_division=0)
            rec  = recall_score(y, yhat)
            candidates.append((g, prec, rec, tp, fp, fn, tn))
    thr_fp = float(sorted(candidates, key=lambda t: (t[1], t[2]), reverse=True)[0][0]) if candidates else None

    return thr_rec, thr_fp, thr_youden

# --- Pick thresholds ---
thr_rec80, thr_fp10, thr_youden = pick_thresholds(y_true, y_prob, recall_target=0.80, fpr_cap=0.10)

# Fallbacks if constraints can’t be met
if thr_rec80 is None: thr_rec80 = 0.0      # lowest threshold → highest recall
if thr_fp10 is None:  thr_fp10  = 1.0      # highest threshold → lowest FPR

# Compute metrics at each operating point + default 0.50
m_rec80  = metrics_at(y_true, y_prob, thr_rec80)
m_fp10   = metrics_at(y_true, y_prob, thr_fp10)
m_youden = metrics_at(y_true, y_prob, thr_youden)
m_def    = metrics_at(y_true, y_prob, 0.50)

# --- Plot three panels ---
def plot_cm(ax, m, title):
    tn, fp, fn, tp = m["TN"], m["FP"], m["FN"], m["TP"]
    cm = np.array([[tn, fp],[fn, tp]])
    im = ax.imshow(cm, cmap="Blues")
    ax.set_title(title, fontsize=12, fontweight='bold')
    ax.set_xticks([0,1]); ax.set_yticks([0,1])
    ax.set_xticklabels(['Pred 0','Pred 1']); ax.set_yticklabels(['True 0','True 1'])
    for (i,j), v in np.ndenumerate(cm):
        ax.text(j, i, str(v), ha='center', va='center', fontsize=13, fontweight='bold')
    sub = (f"thr={m['threshold']:.2f} | "
           f"Prec={m['Precision']:.2f} | Rec={m['Recall']:.2f} | "
           f"Spec={m['Specificity']:.2f} | FPR={m['FPR']:.2f}")
    ax.set_xlabel(sub, fontsize=10)

fig, axes = plt.subplots(1, 3, figsize=(14, 4.8))
plot_cm(axes[0], m_rec80,  "Safety-first: Recall ≥ 0.80")
plot_cm(axes[1], m_fp10,   "FP-conservative: FPR ≤ 0.10")
plot_cm(axes[2], m_youden, "Balanced: Youden J")
plt.tight_layout()
plt.show()

# --- Comparison table (incl. Default 0.50) ---
comp = pd.DataFrame([
    {"Setting":"Recall≥0.80", **m_rec80},
    {"Setting":"FP≤10%",     **m_fp10},
    {"Setting":"Youden J",   **m_youden},
    {"Setting":"Default 0.50", **m_def}
])[["Setting","threshold","TP","FP","FN","TN","Accuracy","Precision","Recall","Specificity","F1","FPR"]]

print("📊 Operating point comparison")
display(comp.style.format({
    "threshold":"{:.2f}", "Accuracy":"{:.3f}", "Precision":"{:.3f}",
    "Recall":"{:.3f}", "Specificity":"{:.3f}", "F1":"{:.3f}", "FPR":"{:.3f}"
}))

# ================================================
# 🔁 Train + Evaluate Logistic Models (24h & 72h)
#    — includes SBP, chronic dz, discharge timing
# ================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    roc_curve, roc_auc_score,
    precision_recall_curve, average_precision_score,
    confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
)

# ------------------------------------------------
# 0) Load data
# ------------------------------------------------
def try_load_df():
    global df
    if 'df' in globals():
        return df.copy()
    # fallback: try BQ if available
    if 'bqclient' in globals() and 'sql' in globals():
        return bqclient.query(sql).to_dataframe()
    raise RuntimeError("No dataframe `df` found and no (bqclient, sql) to query.")

data = try_load_df()
print("Data shape:", data.shape)

# ------------------------------------------------
# 1) Define features (use only those that exist)
# ------------------------------------------------
NUMERIC_CANDIDATES = [
    'any_presser_6h',
    'hr_cv6h','rr_cv6h','map_cv6h','sbp_cv6h',
    'hr_last','rr_last','map_last','sbp_last',
    'hrs_since_presser_off','hrs_since_extubation',
    'icu_los_hours','age_at_transfer','prior_icu_bounces_in_hadm',
    'discharge_after_5pm','discharge_weekend','discharge_hour'
]
CATEG_CANDIDATES = [
    'gender','insurance','marital_status','language','first_careunit_after_icu',
    'discharge_dow'  # 1..7 per BigQuery
]
CHRONIC_FLAGS = ['has_cardiovascular','has_diabetes','has_copd','has_ckd']

# keep only existing columns
num_cols = [c for c in NUMERIC_CANDIDATES + CHRONIC_FLAGS if c in data.columns]
cat_cols = [c for c in CATEG_CANDIDATES if c in data.columns]

LABELS = {
    "24h": "label_readmit_24h",
    "72h": "label_readmit_72h"
}
available = {k:v for k,v in LABELS.items() if v in data.columns}
if not available:
    raise ValueError("No label_readmit_24h or label_readmit_72h in dataframe.")

# ------------------------------------------------
# 2) Build pipeline (impute → scale → OHE → LR)
# ------------------------------------------------
num_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])
cat_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('ohe', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

pre = ColumnTransformer([
    ('num', num_pipe, num_cols),
    ('cat', cat_pipe, cat_cols)
])

clf = LogisticRegression(
    class_weight='balanced',
    solver='liblinear',
    max_iter=1000,
    random_state=42
)

pipe = Pipeline([
    ('pre', pre),
    ('clf', clf)
])

# ------------------------------------------------
# 3) Helpers: eval & plots
# ------------------------------------------------
def evaluate_model(df, label_col, threshold=0.35, title=""):
    X = df[num_cols + cat_cols].copy()
    y = df[label_col].astype(int).values

    pipe.fit(X, y)
    y_prob = pipe.predict_proba(X)[:,1]

    # AUCs
    auc = roc_auc_score(y, y_prob)
    ap  = average_precision_score(y, y_prob)

    # Threshold metrics
    y_pred = (y_prob >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y, y_pred).ravel()
    acc = accuracy_score(y, y_pred)
    ppv = precision_score(y, y_pred, zero_division=0)
    sen = recall_score(y, y_pred)
    f1  = f1_score(y, y_pred)
    spec = tn/(tn+fp) if (tn+fp)>0 else np.nan
    fpr_thr = fp/(fp+tn) if (fp+tn)>0 else np.nan

    # ROC/PR curves
    fpr, tpr, _ = roc_curve(y, y_prob)
    prec, rec, _ = precision_recall_curve(y, y_prob)

    fig, ax = plt.subplots(1,2,figsize=(10,4))
    ax[0].plot(fpr, tpr, lw=2, label=f"AUC={auc:.3f}")
    ax[0].plot([0,1],[0,1],'--',color='gray')
    ax[0].set_xlabel("False Positive Rate"); ax[0].set_ylabel("True Positive Rate")
    ax[0].set_title(f"ROC — {title}"); ax[0].legend()

    ax[1].plot(rec, prec, lw=2)
    ax[1].set_xlabel("Recall"); ax[1].set_ylabel("Precision")
    ax[1].set_title(f"PR — {title} (AUC-PR={ap:.3f})")
    plt.tight_layout(); plt.show()

    # Confusion matrix (counts)
    cm = np.array([[tn, fp],[fn, tp]])
    fig, ax = plt.subplots(figsize=(5,4.2))
    im = ax.imshow(cm, cmap='Blues')
    for (i,j), v in np.ndenumerate(cm):
        ax.text(j,i,str(v),ha='center',va='center',fontsize=13,fontweight='bold')
    ax.set_title(f"Confusion @ thr={threshold:.2f} — {title}")
    ax.set_xticks([0,1]); ax.set_xticklabels(['Pred 0','Pred 1'])
    ax.set_yticks([0,1]); ax.set_yticklabels(['True 0','True 1'])
    plt.colorbar(im, fraction=0.046, pad=0.04); plt.tight_layout(); plt.show()

    # Threshold sweep: Youden J & Recall target
    fpr_s, tpr_s, thr_s = roc_curve(y, y_prob)
    J = tpr_s - fpr_s
    thr_youden = thr_s[np.argmax(J)]
    # Find smallest threshold achieving recall >= 0.80
    prec_s, rec_s, thr_pr = precision_recall_curve(y, y_prob)
    thr_rec80 = None
    for r, t in zip(rec_s, np.r_[thr_pr, [thr_pr[-1]]]):
        if r >= 0.80:
            thr_rec80 = t; break

    # Feature names & odds ratios
    ohe = pipe.named_steps['pre'].named_transformers_.get('cat', None)
    cat_names = ohe.named_steps['ohe'].get_feature_names_out(cat_cols).tolist() if ohe else []
    feature_names = num_cols + cat_names
    coefs = pipe.named_steps['clf'].coef_.ravel()
    or_table = pd.DataFrame({
        "Feature": feature_names,
        "OddsRatio": np.exp(coefs)
    }).sort_values("OddsRatio", ascending=False)

    metrics = {
        "pos_rate": float(np.mean(y)),
        "AUC": float(auc),
        "AUC_PR": float(ap),
        "Threshold_eval": float(threshold),
        "TP": int(tp), "FP": int(fp), "FN": int(fn), "TN": int(tn),
        "Accuracy": float(acc), "Precision": float(ppv),
        "Recall": float(sen), "Specificity": float(spec),
        "F1": float(f1), "FPR": float(fpr_thr),
        "Thr_Youden": float(thr_youden),
        "Thr_Recall80": float(thr_rec80) if thr_rec80 is not None else np.nan
    }

    print("🔢 Metrics:", {k:(round(v,3) if isinstance(v,float) else v) for k,v in metrics.items()})
    print("\n🔎 Top 20 Odds Ratios:")
    display(or_table.head(20))

    return {"pipe": pipe, "y": y, "y_prob": y_prob, "metrics": metrics, "or_table": or_table}

# ------------------------------------------------
# 4) Run for 24h and 72h
# ------------------------------------------------
results = {}
for win, lab in available.items():
    print(f"\n==================== {win} model ====================")
    results[win] = evaluate_model(data, label_col=lab, threshold=0.35, title=f"Readmission ≤{win}")

# ------------------------------------------------
# 5) Compare windows
# ------------------------------------------------
comp = pd.DataFrame([
    {"Window": win, **results[win]["metrics"]}
    for win in results
])[["Window","pos_rate","AUC","AUC_PR","Threshold_eval","TP","FP","FN","TN",
   "Accuracy","Precision","Recall","Specificity","F1","FPR","Thr_Youden","Thr_Recall80"]]

display(comp.style.format({
    "pos_rate":"{:.3f}","AUC":"{:.3f}","AUC_PR":"{:.3f}",
    "Accuracy":"{:.3f}","Precision":"{:.3f}","Recall":"{:.3f}",
    "Specificity":"{:.3f}","F1":"{:.3f}","FPR":"{:.3f}",
    "Thr_Youden":"{:.2f}","Thr_Recall80":"{:.2f}"
}))

# ------------------------------------------------
# 6) Quick narrative for the slide (top predictors)
# ------------------------------------------------
for win in results:
    print(f"\n📝 Slide bullets — Readmission ≤{win}")
    top = results[win]["or_table"]
    top_up   = top.sort_values("OddsRatio", ascending=False).head(3)
    top_down = top.sort_values("OddsRatio", ascending=True).head(2)
    bullets = []
    for _, r in top_up.iterrows():
        bullets.append(f"• Higher {r['Feature']} → OR {r['OddsRatio']:.2f}")
    for _, r in top_down.iterrows():
        bullets.append(f"• Lower {r['Feature']} → OR {r['OddsRatio']:.2f}")
    print("\n".join(bullets))

# ================================================
# 🎨 Visual Comparison — ROC & PR Curves (24h vs 72h)
# ================================================
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, precision_recall_curve, auc

# Collect available models from previous run
available_models = [k for k in ["24h", "72h"] if k in results]

if not available_models:
    raise ValueError("No trained models found in `results`. Please run the training cell first.")

plt.figure(figsize=(12,5))

# ------------------------------------------------
# 🩺 ROC Curves
# ------------------------------------------------
plt.subplot(1,2,1)
for win in available_models:
    y_true = results[win]["y"]
    y_prob = results[win]["y_prob"]
    fpr, tpr, _ = roc_curve(y_true, y_prob)
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, lw=2, label=f"{win} (AUC = {roc_auc:.3f})")

plt.plot([0,1],[0,1],'--',color='gray',lw=1)
plt.xlabel("False Positive Rate (1 - Specificity)")
plt.ylabel("True Positive Rate (Recall)")
plt.title("ROC Curve — Model Discrimination Ability")
plt.legend()
plt.grid(alpha=0.3)

# ------------------------------------------------
# 💗 PR Curves
# ------------------------------------------------
plt.subplot(1,2,2)
for win in available_models:
    y_true = results[win]["y"]
    y_prob = results[win]["y_prob"]
    prec, rec, _ = precision_recall_curve(y_true, y_prob)
    pr_auc = auc(rec, prec)
    plt.plot(rec, prec, lw=2, label=f"{win} (AUC-PR = {pr_auc:.3f})")

# Baseline (random model)
for win in available_models:
    base_rate = results[win]["metrics"]["pos_rate"]
    plt.hlines(base_rate, 0, 1, colors='gray', linestyles='--', alpha=0.5,
               label=f"Baseline prevalence ({base_rate:.2%})")
    break

plt.xlabel("Recall (Sensitivity)")
plt.ylabel("Precision (PPV)")
plt.title("Precision–Recall Curve — Alert Quality Under Imbalance")
plt.legend()
plt.grid(alpha=0.3)

plt.suptitle("📈 ROC & PR Curves — ICU Readmission Models (24h vs 72h)", fontsize=14)
plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()

# 🧮 Chronic disease prevalence by readmission status
chronic_vars = ['has_cardiovascular','has_diabetes','has_copd','has_ckd']
targets = ['label_readmit_24h','label_readmit_72h']

for label in targets:
    if label in df.columns:
        print(f"\n🔹 Chronic disease prevalence for {label}:")
        tab = df.groupby(label)[chronic_vars].mean().T
        tab.columns = ['No Readmit','Readmit']
        tab['Δ (Readmit - No)'] = tab['Readmit'] - tab['No Readmit']
        display((tab*100).round(1))

import matplotlib.pyplot as plt
import seaborn as sns

if 'label_readmit_72h' in df.columns:
    chronic_summary = (
        df.groupby('label_readmit_72h')[chronic_vars]
          .mean()
          .T.reset_index()
          .rename(columns={'index':'Condition',0:'No Readmit',1:'Readmit'})
    )
    chronic_summary = chronic_summary.melt(id_vars='Condition', var_name='Group', value_name='Rate')
    chronic_summary['Rate'] = chronic_summary['Rate'] * 100

    plt.figure(figsize=(7,4))
    sns.barplot(data=chronic_summary, x='Condition', y='Rate', hue='Group', palette='Set2')
    plt.title('Chronic Disease Prevalence — 72h Readmission vs Non-Readmit')
    plt.ylabel('% of Patients')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

!pip install python-pptx

from pptx import Presentation
from pptx.util import Inches, Pt

prs = Presentation()

def add_slide(title, bullets):
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = title
    body = slide.placeholders[1]
    tf = body.text_frame
    tf.clear()
    for b in bullets:
        p = tf.add_paragraph()
        p.text = b
        p.level = 0

# --- Slides ---
add_slide("Aster Digital Health — ICU Readmission Predictive Model", [
    "AI-driven analysis to prevent early ICU readmissions",
    "MIMIC-IV v3.1 — ICU→Floor cohort (30K+ transfers)",
    "Clinical Data Science × Engineering × Quality"
])

add_slide("Business Problem", [
    "6 % of ICU→Floor patients readmitted ≤ 24 h",
    "Each event costs $6K–12K and 1–2 ICU bed-days",
    "No standardized transfer-readiness criteria"
])

add_slide("Study Objective", [
    "Predict ICU readmissions ≤ 24 h and ≤ 72 h",
    "Identify physiologic and operational drivers",
    "Enable early intervention via AI risk scoring"
])

add_slide("Data Cohort & Features", [
    "Vitals: HR, RR, MAP, SBP + CVs (last 6 h)",
    "Therapies: Vasopressors, extubation timing",
    "Comorbidities: CKD, CVD, COPD, Diabetes",
    "Timing: discharge hour, weekend flag",
    "Context: prior ICU bounces, ICU LOS"
])

add_slide("Vital Instability Insights", [
    "↑ RR & MAP variability → higher readmit odds",
    "↑ SBP variability = strongest instability signal",
    "↓ HR variability → possible medication effect"
])

add_slide("Chronic Disease Findings", [
    "CKD patients 2× more likely to return early",
    "CVD +13 % risk vs non-readmits",
    "COPD & Diabetes = moderate elevation"
])

add_slide("Discharge Timing Effects", [
    "After 5 PM → 40 % higher readmission odds",
    "Weekend discharges → 1.3× higher risk",
    "Operational timing is a modifiable factor"
])

add_slide("Correlation Patterns", [
    "MAP, RR, SBP variability cluster together",
    "Weak correlation with age or gender",
    "ICU LOS + pressor use linked to readmission"
])

add_slide("Model Performance", [
    "24 h AUC = 0.82  (PR = 0.28)  Recall = 0.74",
    "72 h AUC = 0.84  (PR = 0.32)  Recall = 0.78",
    "Strong discrimination at 6–9 % event rate"
])

add_slide("Top Predictors (Odds Ratios)", [
    "Discharge Lounge → OR 93",
    "ED Observation → OR 60",
    "CKD → OR 2.0  |  CVD → OR 1.6",
    "Discharge after 5 PM → OR 1.4",
    "SBP variability → physiologic risk"
])

add_slide("Bias & Fairness Audit", [
    "Gender/insurance bias < 5 pp gap",
    "Language variance = data imbalance",
    "Stable performance across groups"
])

add_slide("Operational Integration", [
    "Hourly scoring → risk in ICU checklist",
    "> 0.35 → senior review + 6–12 h observation",
    "High-risk discharges → auto tele-follow-up"
])

add_slide("Impact Projection", [
    "24 h readmits ↓ 6 % → 4 % (-30 %)",
    "30-day readmits ↓ 9 % → 7 % (-22 %)",
    "≈ 450 bed-days freed / yr  ($0.5–1 M saved)"
])

add_slide("Recommendations", [
    "✅ Tighten discharge checks for pressor/extubation cases",
    "✅ Avoid late/weekend borderline discharges",
    "✅ Embed AI risk into EHR workflows",
    "✅ Quarterly model drift + fairness review"
])

add_slide("Summary & Next Steps", [
    "AUC > 0.8 model accurately predicts risk",
    "CKD, CVD, SBP variability + timing key drivers",
    "Integration → 25–30 % reduction in readmits",
    "Next: Pilot → Dashboard → Rollout Q2 2025"
])

add_slide("Appendix — Charts to Insert", [
    "• Readmission rates (24 h / 72 h)",
    "• Vital variability boxplots (HR RR MAP SBP)",
    "• Comorbidity bar chart",
    "• ROC & PR curves",
    "• Confusion matrix with counts",
    "• Odds ratio bar plot"
])

prs.save("/content/Aster_ICU_Readmission_Predictive_Model_Final.pptx")
print("✅ PowerPoint saved as 'Aster_ICU_Readmission_Predictive_Model_Final.pptx'")

"""# Task
Evaluate and compare the performance of various machine learning models (e.g., Random Forest, Gradient Boosting, Support Vector Machines) for predicting ICU readmission within 24 and 72 hours, using metrics such as ROC AUC, PR AUC, and F1-score, to identify the most promising model(s) for further optimization.

## Advanced Feature Engineering

### Subtask:
Explore and create more sophisticated features from the existing dataset, such as interaction terms, polynomial features, or features derived from deeper clinical domain knowledge. Review current features for redundancy, multicollinearity, or areas where more granular information could be beneficial.

## Advanced Feature Engineering

### Subtask:
Explore and create more sophisticated features from the existing dataset, such as interaction terms, polynomial features, or features derived from deeper clinical domain knowledge. Review current features for redundancy, multicollinearity, or areas where more granular information could be beneficial.

#### Instructions
1. Review the existing features in the DataFrame `df` and consider how they might be combined or transformed to create more predictive signals.
2. Identify potential interaction terms between existing numerical or categorical features (e.g., `age_at_transfer` * `has_cardiovascular`, or interactions between `any_presser_6h` and vital sign variability metrics).
3. Consider creating polynomial features for highly influential continuous variables (e.g., `age_at_transfer` squared or cubed).
4. Explore if any existing categorical variables can be further refined or combined based on clinical relevance.
5. Document any new features you decide to create, including their derivation and the reasoning behind their potential predictive power.

## Advanced Feature Engineering

### Subtask:
Explore and create more sophisticated features from the existing dataset, such as interaction terms, polynomial features, or features derived from deeper clinical domain knowledge. Review current features for redundancy, multicollinearity, or areas where more granular information could be beneficial.

#### Instructions
1. Review the existing features in the DataFrame `df` and consider how they might be combined or transformed to create more predictive signals.
2. Identify potential interaction terms between existing numerical or categorical features (e.g., `age_at_transfer` * `has_cardiovascular`, or interactions between `any_presser_6h` and vital sign variability metrics).
3. Consider creating polynomial features for highly influential continuous variables (e.g., `age_at_transfer` squared or cubed).
4. Explore if any existing categorical variables can be further refined or combined based on clinical relevance.
5. Document any new features you decide to create, including their derivation and the reasoning behind their potential predictive power.

## Advanced Feature Engineering

### Subtask:
Explore and create more sophisticated features from the existing dataset, such as interaction terms, polynomial features, or features derived from deeper clinical domain knowledge. Review current features for redundancy, multicollinearity, or areas where more granular information could be beneficial.

#### Instructions
1. Review the existing features in the DataFrame `df` and consider how they might be combined or transformed to create more predictive signals.
2. Identify potential interaction terms between existing numerical or categorical features (e.g., `age_at_transfer` * `has_cardiovascular`, or interactions between `any_presser_6h` and vital sign variability metrics).
3. Consider creating polynomial features for highly influential continuous variables (e.g., `age_at_transfer` squared or cubed).
4. Explore if any existing categorical variables can be further refined or combined based on clinical relevance.
5. Document any new features you decide to create, including their derivation and the reasoning behind their potential predictive power.

## Advanced Feature Engineering

### Subtask:
Explore and create more sophisticated features from the existing dataset, such as interaction terms, polynomial features, or features derived from deeper clinical domain knowledge. Review current features for redundancy, multicollinearity, or areas where more granular information could be beneficial.

#### Instructions
1. Review the existing features in the DataFrame `df` and consider how they might be combined or transformed to create more predictive signals.
2. Identify potential interaction terms between existing numerical or categorical features (e.g., `age_at_transfer` * `has_cardiovascular`, or interactions between `any_presser_6h` and vital sign variability metrics).
3. Consider creating polynomial features for highly influential continuous variables (e.g., `age_at_transfer` squared or cubed).
4. Explore if any existing categorical variables can be further refined or combined based on clinical relevance.
5. Document any new features you decide to create, including their derivation and the reasoning behind their potential predictive power.

## Advanced Feature Engineering

### Subtask:
Explore and create more sophisticated features from the existing dataset, such as interaction terms, polynomial features, or features derived from deeper clinical domain knowledge. Review current features for redundancy, multicollinearity, or areas where more granular information could be beneficial.

#### Instructions
1. Review the existing features in the DataFrame `df` and consider how they might be combined or transformed to create more predictive signals.
2. Identify potential interaction terms between existing numerical or categorical features (e.g., `age_at_transfer` * `has_cardiovascular`, or interactions between `any_presser_6h` and vital sign variability metrics).
3. Consider creating polynomial features for highly influential continuous variables (e.g., `age_at_transfer` squared or cubed).
4. Explore if any existing categorical variables can be further refined or combined based on clinical relevance.
5. Document any new features you decide to create, including their derivation and the reasoning behind their potential predictive power.

## Advanced Feature Engineering

### Subtask:
Explore and create more sophisticated features from the existing dataset, such as interaction terms, polynomial features, or features derived from deeper clinical domain knowledge. Review current features for redundancy, multicollinearity, or areas where more granular information could be beneficial.

#### Instructions
1. Review the existing features in the DataFrame `df` and consider how they might be combined or transformed to create more predictive signals.
2. Identify potential interaction terms between existing numerical or categorical features (e.g., `age_at_transfer` * `has_cardiovascular`, or interactions between `any_presser_6h` and vital sign variability metrics).
3. Consider creating polynomial features for highly influential continuous variables (e.g., `age_at_transfer` squared or cubed).
4. Explore if any existing categorical variables can be further refined or combined based on clinical relevance.
5. Document any new features you decide to create, including their derivation and the reasoning behind their potential predictive power.

## Advanced Feature Engineering

### Subtask:
Explore and create more sophisticated features from the existing dataset, such as interaction terms, polynomial features, or features derived from deeper clinical domain knowledge. Review current features for redundancy, multicollinearity, or areas where more granular information could be beneficial.

#### Instructions
1. Review the existing features in the DataFrame `df` and consider how they might be combined or transformed to create more predictive signals.
2. Identify potential interaction terms between existing numerical or categorical features (e.g., `age_at_transfer` * `has_cardiovascular`, or interactions between `any_presser_6h` and vital sign variability metrics).
3. Consider creating polynomial features for highly influential continuous variables (e.g., `age_at_transfer` squared or cubed).
4. Explore if any existing categorical variables can be further refined or combined based on clinical relevance.
5. Document any new features you decide to create, including their derivation and the reasoning behind their potential predictive power.

### Reasoning:
To enhance the predictive power of our model and capture more complex relationships within the data, we will create advanced features. These include:

1.  **Interaction Term: `age_cardio_interaction`**: This term will combine `age_at_transfer` and `has_cardiovascular`. Cardiovascular risk often increases with age, and this interaction might better capture the combined burden on readmission risk than either feature alone.
2.  **Interaction Term: `pressor_vitals_cv_interaction`**: This term will combine `any_presser_6h` (a binary indicator of vasopressor use) with `map_cv6h` (MAP variability) and `sbp_cv6h` (SBP variability). Patients on vasopressors might exhibit different patterns or sensitivities to vital sign instability, making their interaction clinically relevant.
3.  **Polynomial Feature: `age_squared`**: Squaring `age_at_transfer` can capture non-linear relationships, as the impact of age on health outcomes (like readmission) may not be purely linear but might accelerate in older age groups.
4.  **Categorical Combination: `discharge_timing_risk`**: Combining `discharge_after_5pm` and `discharge_weekend` into a single high-risk category could better represent the operational challenges and reduced staffing often associated with these discharge times.

These features are chosen to potentially uncover latent patterns and provide the model with richer, more nuanced information.

### Reasoning:
To enhance the predictive power of our model and capture more complex relationships within the data, we will create advanced features. These include:

1.  **Interaction Term: `age_cardio_interaction`**: This term will combine `age_at_transfer` and `has_cardiovascular`. Cardiovascular risk often increases with age, and this interaction might better capture the combined burden on readmission risk than either feature alone.
2.  **Interaction Term: `pressor_vitals_cv_interaction`**: This term will combine `any_presser_6h` (a binary indicator of vasopressor use) with `map_cv6h` (MAP variability) and `sbp_cv6h` (SBP variability). Patients on vasopressors might exhibit different patterns or sensitivities to vital sign instability, making their interaction clinically relevant.
3.  **Polynomial Feature: `age_squared`**: Squaring `age_at_transfer` can capture non-linear relationships, as the impact of age on health outcomes (like readmission) may not be purely linear but might accelerate in older age groups.
4.  **Categorical Combination: `discharge_timing_risk`**: Combining `discharge_after_5pm` and `discharge_weekend` into a single high-risk category could better represent the operational challenges and reduced staffing often associated with these discharge times.

These features are chosen to potentially uncover latent patterns and provide the model with richer, more nuanced information.

**Reasoning**:
Now that the reasoning for advanced features is established, I will implement the creation of these new features directly into the DataFrame `df` based on the specified interactions, polynomial transformations, and categorical combinations.
"""

df_engineered = df.copy()

# 1. Interaction Term: age_cardio_interaction
# Multiply age_at_transfer by has_cardiovascular (assuming has_cardiovascular is 0 or 1)
if 'age_at_transfer' in df_engineered.columns and 'has_cardiovascular' in df_engineered.columns:
    df_engineered['age_cardio_interaction'] = df_engineered['age_at_transfer'] * df_engineered['has_cardiovascular']
    print("Created 'age_cardio_interaction' feature.")

# 2. Interaction Term: pressor_vitals_cv_interaction
# Combine any_presser_6h with MAP and SBP variability. Handle potential NaNs for CVs.
if 'any_presser_6h' in df_engineered.columns and 'map_cv6h' in df_engineered.columns and 'sbp_cv6h' in df_engineered.columns:
    # Fill NaNs for CVs before multiplication to avoid propagating NaNs, using 0 as a neutral value for 'no variability'
    df_engineered['pressor_vitals_cv_interaction'] = \
        df_engineered['any_presser_6h'] * \
        (df_engineered['map_cv6h'].fillna(0) + df_engineered['sbp_cv6h'].fillna(0))
    print("Created 'pressor_vitals_cv_interaction' feature.")

# 3. Polynomial Feature: age_squared
# Square the age_at_transfer to capture non-linear effects.
if 'age_at_transfer' in df_engineered.columns:
    df_engineered['age_squared'] = df_engineered['age_at_transfer']**2
    print("Created 'age_squared' feature.")

# 4. Categorical Combination: discharge_timing_risk
# Create a binary flag for high-risk discharge times (after 5 PM AND/OR on a weekend).
if 'discharge_after_5pm' in df_engineered.columns and 'discharge_weekend' in df_engineered.columns:
    df_engineered['discharge_timing_risk'] = (
        (df_engineered['discharge_after_5pm'] == 1) | (df_engineered['discharge_weekend'] == 1)
    ).astype(int)
    print("Created 'discharge_timing_risk' feature.")

print("Advanced features engineered successfully.")
print("DataFrame head with new features:")
display(df_engineered.head())

sql_summary = """
WITH cohort AS (
  SELECT
    subject_id,
    hadm_id,
    stay_id,
    label_readmit_24h,
    label_readmit_72h
  FROM `physionet-data.your_dataset.icu_readmission_features`  -- change to your dataset
)
SELECT
  COUNT(DISTINCT subject_id) AS unique_icu_patients,
  COUNT(stay_id) AS total_icu_stays,
  SUM(CASE WHEN label_readmit_24h = 1 THEN 1 ELSE 0 END) AS readmit_24h_count,
  SUM(CASE WHEN label_readmit_72h = 1 THEN 1 ELSE 0 END) AS readmit_72h_count,
  ROUND(SUM(CASE WHEN label_readmit_24h = 1 THEN 1 ELSE 0 END)*100.0 / COUNT(stay_id), 2) AS readmit_24h_rate,
  ROUND(SUM(CASE WHEN label_readmit_72h = 1 THEN 1 ELSE 0 END)*100.0 / COUNT(stay_id), 2) AS readmit_72h_rate
FROM cohort
"""

df_summary = bq_to_df_safe(sql)
print(f"Rows fetched: {len(df):,}")
df_summary.head()

df_summary.columns = df_summary.columns.str.strip().str.lower()
print(df_summary.columns.tolist())
